FROM golang:alpine

RUN apk add --no-cache \
    gcc \
    libc-dev \
    librdkafka-dev=1.8.2-r0 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
    readline-dev

RUN mkdir /app
COPY go.mod /app
WORKDIR /app

RUN go mod download
RUN go get -u github.com/nathany/looper
