FROM golang:alpine

RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories
RUN apk upgrade --update-cache --available
RUN apk add --no-cache \
    gcc \
    libc-dev \
    librdkafka-dev=1.8.0-r0 \
    readline-dev

RUN mkdir /app
COPY go.mod /app
WORKDIR /app

RUN go mod download
RUN go get -u github.com/nathany/looper
