from _typeshed import Incomplete

class AppData:
    param_types: Incomplete
    def __init__(self, application_tracking_enabled: bool = None, advertiser_tracking_enabled: str = None, campaign_ids: str = None, consider_views: bool = None, extinfo: ExtendedDeviceInfo = None, include_dwell_data: bool = None, include_video_data: bool = None, install_referrer: str = None, installer_package: str = None, receipt_data: str = None, url_schemes: str = None, windows_attribution_id: str = None) -> None: ...
    @property
    def application_tracking_enabled(self): ...
    @application_tracking_enabled.setter
    def application_tracking_enabled(self, application_tracking_enabled) -> None: ...
    @property
    def advertiser_tracking_enabled(self): ...
    @advertiser_tracking_enabled.setter
    def advertiser_tracking_enabled(self, advertiser_tracking_enabled) -> None: ...
    @property
    def campaign_ids(self): ...
    @campaign_ids.setter
    def campaign_ids(self, campaign_ids) -> None: ...
    @property
    def consider_views(self): ...
    @consider_views.setter
    def consider_views(self, consider_views) -> None: ...
    @property
    def extinfo(self): ...
    @extinfo.setter
    def extinfo(self, extinfo) -> None: ...
    @property
    def include_dwell_data(self): ...
    @include_dwell_data.setter
    def include_dwell_data(self, include_dwell_data) -> None: ...
    @property
    def include_video_data(self): ...
    @include_video_data.setter
    def include_video_data(self, include_video_data) -> None: ...
    @property
    def install_referrer(self): ...
    @install_referrer.setter
    def install_referrer(self, install_referrer) -> None: ...
    @property
    def installer_package(self): ...
    @installer_package.setter
    def installer_package(self, installer_package) -> None: ...
    @property
    def receipt_data(self): ...
    @receipt_data.setter
    def receipt_data(self, receipt_data) -> None: ...
    @property
    def url_schemes(self): ...
    @url_schemes.setter
    def url_schemes(self, url_schemes) -> None: ...
    @property
    def windows_attribution_id(self): ...
    @windows_attribution_id.setter
    def windows_attribution_id(self, windows_attribution_id) -> None: ...
    def normalize(self): ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
