from _typeshed import Incomplete
from collections.abc import Generator
from facebook_business.adobjects.serverside.util import Util as Util

class BatchProcessor:
    batch_size: Incomplete
    concurrent_requests: Incomplete
    def __init__(self, batch_size: int = 50, concurrent_requests: int = 4) -> None: ...
    def process_event_requests(self, event_requests_async) -> None: ...
    async def process_event_requests_generator(self, event_requests_async) -> Generator[Incomplete, None, None]: ...
    def process_events(self, event_request_async_to_clone, events) -> None: ...
    async def process_events_generator(self, event_request_async_to_clone, events) -> Generator[Incomplete, None, None]: ...
