from _typeshed import Incomplete
from facebook_business.adobjects.serverside.delivery_category import DeliveryCategory as DeliveryCategory

class Content:
    param_types: Incomplete
    def __init__(self, product_id: str = None, quantity: int = None, item_price: float = None, title: str = None, description: str = None, brand: str = None, category: str = None, delivery_category: str = None) -> None: ...
    @property
    def product_id(self): ...
    @product_id.setter
    def product_id(self, product_id) -> None: ...
    @property
    def quantity(self): ...
    @quantity.setter
    def quantity(self, quantity) -> None: ...
    @property
    def item_price(self): ...
    @item_price.setter
    def item_price(self, item_price) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, title) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description) -> None: ...
    @property
    def brand(self): ...
    @brand.setter
    def brand(self, brand) -> None: ...
    @property
    def category(self): ...
    @category.setter
    def category(self, category) -> None: ...
    @property
    def delivery_category(self): ...
    @delivery_category.setter
    def delivery_category(self, delivery_category) -> None: ...
    def normalize(self): ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
