from _typeshed import Incomplete
from facebook_business.adobjects.serverside.content import Content as Content
from facebook_business.adobjects.serverside.delivery_category import DeliveryCategory as DeliveryCategory
from facebook_business.adobjects.serverside.normalize import Normalize as Normalize

class CustomData:
    param_types: Incomplete
    def __init__(self, value: str = None, currency: str = None, content_name: str = None, content_category: content_ids = None, content_ids: List[str] = None, contents: List[Content] = None, content_type: str = None, order_id: str = None, predicted_ltv: float = None, num_items: int = None, status: str = None, search_string: str = None, delivery_category: DeliveryCategory = None, item_number: str = None, custom_properties: dict = {}) -> None: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, value) -> None: ...
    @property
    def currency(self): ...
    @currency.setter
    def currency(self, currency) -> None: ...
    @property
    def content_name(self): ...
    @content_name.setter
    def content_name(self, content_name) -> None: ...
    @property
    def content_category(self): ...
    @content_category.setter
    def content_category(self, content_category) -> None: ...
    @property
    def content_ids(self): ...
    @content_ids.setter
    def content_ids(self, content_ids) -> None: ...
    @property
    def contents(self): ...
    @contents.setter
    def contents(self, contents) -> None: ...
    @property
    def content_type(self): ...
    @content_type.setter
    def content_type(self, content_type) -> None: ...
    @property
    def order_id(self): ...
    @order_id.setter
    def order_id(self, order_id) -> None: ...
    @property
    def predicted_ltv(self): ...
    @predicted_ltv.setter
    def predicted_ltv(self, predicted_ltv) -> None: ...
    @property
    def num_items(self): ...
    @num_items.setter
    def num_items(self, num_items) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status) -> None: ...
    @property
    def search_string(self): ...
    @search_string.setter
    def search_string(self, search_string) -> None: ...
    @property
    def delivery_category(self): ...
    @delivery_category.setter
    def delivery_category(self, delivery_category) -> None: ...
    @property
    def item_number(self): ...
    @item_number.setter
    def item_number(self, item_number) -> None: ...
    @property
    def custom_properties(self): ...
    @custom_properties.setter
    def custom_properties(self, custom_properties) -> None: ...
    def add_custom_property(self, key, value) -> None: ...
    def normalize(self): ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
