from _typeshed import Incomplete

class EventResponse:
    param_types: Incomplete
    def __init__(self, events_received: int = None, messages: List[str] = None, fbtrace_id: str = None) -> None: ...
    @property
    def events_received(self): ...
    @events_received.setter
    def events_received(self, events_received) -> None: ...
    @property
    def messages(self): ...
    @messages.setter
    def messages(self, messages) -> None: ...
    @property
    def fbtrace_id(self): ...
    @fbtrace_id.setter
    def fbtrace_id(self, fbtrace_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
