from _typeshed import Incomplete
from facebook_business.adobjects.serverside.event_request import EventRequest as EventRequest
from facebook_business.adobjects.serverside.event_response import EventResponse as EventResponse
from facebook_business.adobjects.serverside.util import Util as Util
from facebook_business.api import FacebookAdsApi as FacebookAdsApi
from facebook_business.session import FacebookSession as FacebookSession

class EventRequestAsync(EventRequest):
    pixel_id: Incomplete
    def __init__(self, pixel_id: Incomplete | None = None, events: Incomplete | None = None, test_event_code: Incomplete | None = None, namespace_id: Incomplete | None = None, upload_id: Incomplete | None = None, upload_tag: Incomplete | None = None, upload_source: Incomplete | None = None, partner_agent: Incomplete | None = None) -> None: ...
    async def create_event(self, session): ...
    async def execute(self): ...
    def normalize(self): ...
    def clone_without_events(self): ...
