from _typeshed import Incomplete

class ExtendedDeviceInfo:
    EXT_INFO_VERSION: int
    APP_PACKAGE_NAME: int
    SHORT_VERSION: int
    LONG_VERSION: int
    OS_VERSION: int
    DEVICE_MODEL_NAME: int
    LOCALE: int
    TIMEZONE_ABBREVIATION: int
    CARRIER: int
    SCREEN_WIDTH: int
    SCREEN_HEIGHT: int
    SCREEN_DENSITY: int
    CPU_CORE_COUNT: int
    TOTAL_DISK_SPACE_GB: int
    FREE_DISK_SPACE_GB: int
    DEVICE_TIME_ZONE: int
    param_types: Incomplete
    def __init__(self, ext_info_version: str = None, app_package_name: str = None, short_version: str = None, long_version: str = None, os_version: str = None, device_model_name: str = None, locale: str = None, timezone_abbreviation: str = None, carrier: str = None, screen_width: int = None, screen_height: int = None, screen_density: str = None, cpu_core_count: int = None, total_disk_space_gb: int = None, free_disk_space_gb: int = None, device_time_zone: str = None) -> None: ...
    @property
    def ext_info_version(self): ...
    @ext_info_version.setter
    def ext_info_version(self, ext_info_version) -> None: ...
    @property
    def app_package_name(self): ...
    @app_package_name.setter
    def app_package_name(self, app_package_name) -> None: ...
    @property
    def short_version(self): ...
    @short_version.setter
    def short_version(self, short_version) -> None: ...
    @property
    def long_version(self): ...
    @long_version.setter
    def long_version(self, long_version) -> None: ...
    @property
    def os_version(self): ...
    @os_version.setter
    def os_version(self, os_version) -> None: ...
    @property
    def device_model_name(self): ...
    @device_model_name.setter
    def device_model_name(self, device_model_name) -> None: ...
    @property
    def locale(self): ...
    @locale.setter
    def locale(self, locale) -> None: ...
    @property
    def timezone_abbreviation(self): ...
    @timezone_abbreviation.setter
    def timezone_abbreviation(self, timezone_abbreviation) -> None: ...
    @property
    def carrier(self): ...
    @carrier.setter
    def carrier(self, carrier) -> None: ...
    @property
    def screen_width(self): ...
    @screen_width.setter
    def screen_width(self, screen_width) -> None: ...
    @property
    def screen_height(self): ...
    @screen_height.setter
    def screen_height(self, screen_height) -> None: ...
    @property
    def screen_density(self): ...
    @screen_density.setter
    def screen_density(self, screen_density) -> None: ...
    @property
    def cpu_core_count(self): ...
    @cpu_core_count.setter
    def cpu_core_count(self, cpu_core_count) -> None: ...
    @property
    def total_disk_space_gb(self): ...
    @total_disk_space_gb.setter
    def total_disk_space_gb(self, total_disk_space_gb) -> None: ...
    @property
    def free_disk_space_gb(self): ...
    @free_disk_space_gb.setter
    def free_disk_space_gb(self, free_disk_space_gb) -> None: ...
    @property
    def device_time_zone(self): ...
    @device_time_zone.setter
    def device_time_zone(self, device_time_zone) -> None: ...
    def normalize(self): ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
