from _typeshed import Incomplete
from facebook_business.adobjects.serverside.gender import Gender as Gender
from facebook_business.adobjects.serverside.normalize import Normalize as Normalize

class UserData:
    multi_value_constructor_err: str
    param_types: Incomplete
    def __init__(self, email: str = None, phone: str = None, gender: Gender = None, date_of_birth: str = None, last_name: str = None, first_name: str = None, city: str = None, state: str = None, country_code: str = None, zip_code: str = None, external_id: str = None, client_ip_address: str = None, client_user_agent: str = None, fbc: str = None, fbp: str = None, subscription_id: str = None, fb_login_id: str = None, lead_id: str = None, f5first: str = None, f5last: str = None, fi: str = None, dobd: str = None, dobm: str = None, doby: str = None, emails: list[str] = None, phones: list[str] = None, genders: list[Gender] = None, dates_of_birth: list[str] = None, last_names: list[str] = None, first_names: list[str] = None, cities: list[str] = None, states: list[str] = None, country_codes: list[str] = None, zip_codes: list[str] = None, external_ids: list[str] = None, madid: str = None, anon_id: str = None, ctwa_clid: str = None, page_id: str = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def emails(self): ...
    @emails.setter
    def emails(self, emails) -> None: ...
    @property
    def phone(self): ...
    @phone.setter
    def phone(self, phone) -> None: ...
    @property
    def phones(self): ...
    @phones.setter
    def phones(self, phones) -> None: ...
    @property
    def gender(self): ...
    @gender.setter
    def gender(self, gender) -> None: ...
    @property
    def genders(self): ...
    @genders.setter
    def genders(self, genders) -> None: ...
    @property
    def date_of_birth(self): ...
    @date_of_birth.setter
    def date_of_birth(self, date_of_birth) -> None: ...
    @property
    def dates_of_birth(self): ...
    @dates_of_birth.setter
    def dates_of_birth(self, dates_of_birth) -> None: ...
    @property
    def last_name(self): ...
    @last_name.setter
    def last_name(self, last_name) -> None: ...
    @property
    def last_names(self): ...
    @last_names.setter
    def last_names(self, last_names) -> None: ...
    @property
    def first_name(self): ...
    @first_name.setter
    def first_name(self, first_name) -> None: ...
    @property
    def first_names(self): ...
    @first_names.setter
    def first_names(self, first_names) -> None: ...
    @property
    def city(self): ...
    @city.setter
    def city(self, city) -> None: ...
    @property
    def cities(self): ...
    @cities.setter
    def cities(self, cities) -> None: ...
    @property
    def state(self): ...
    @state.setter
    def state(self, state) -> None: ...
    @property
    def states(self): ...
    @states.setter
    def states(self, states) -> None: ...
    @property
    def country_code(self): ...
    @country_code.setter
    def country_code(self, country_code) -> None: ...
    @property
    def country_codes(self): ...
    @country_codes.setter
    def country_codes(self, country_codes) -> None: ...
    @property
    def zip_code(self): ...
    @zip_code.setter
    def zip_code(self, zip_code) -> None: ...
    @property
    def zip_codes(self): ...
    @zip_codes.setter
    def zip_codes(self, zip_codes) -> None: ...
    @property
    def external_id(self): ...
    @external_id.setter
    def external_id(self, external_id) -> None: ...
    @property
    def external_ids(self): ...
    @external_ids.setter
    def external_ids(self, external_ids) -> None: ...
    @property
    def client_ip_address(self): ...
    @client_ip_address.setter
    def client_ip_address(self, client_ip_address) -> None: ...
    @property
    def client_user_agent(self): ...
    @client_user_agent.setter
    def client_user_agent(self, client_user_agent) -> None: ...
    @property
    def fbc(self): ...
    @fbc.setter
    def fbc(self, fbc) -> None: ...
    @property
    def fbp(self): ...
    @fbp.setter
    def fbp(self, fbp) -> None: ...
    @property
    def subscription_id(self): ...
    @subscription_id.setter
    def subscription_id(self, subscription_id) -> None: ...
    @property
    def fb_login_id(self): ...
    @fb_login_id.setter
    def fb_login_id(self, fb_login_id) -> None: ...
    @property
    def lead_id(self): ...
    @lead_id.setter
    def lead_id(self, lead_id) -> None: ...
    @property
    def f5first(self): ...
    @f5first.setter
    def f5first(self, f5first) -> None: ...
    @property
    def f5last(self): ...
    @f5last.setter
    def f5last(self, f5last) -> None: ...
    @property
    def fi(self): ...
    @fi.setter
    def fi(self, fi) -> None: ...
    @property
    def dobd(self): ...
    @dobd.setter
    def dobd(self, dobd) -> None: ...
    @property
    def dobm(self): ...
    @dobm.setter
    def dobm(self, dobm) -> None: ...
    @property
    def doby(self): ...
    @doby.setter
    def doby(self, doby) -> None: ...
    @property
    def madid(self): ...
    @madid.setter
    def madid(self, madid) -> None: ...
    @property
    def anon_id(self): ...
    @anon_id.setter
    def anon_id(self, anon_id) -> None: ...
    @property
    def ctwa_clid(self): ...
    @ctwa_clid.setter
    def ctwa_clid(self, ctwa_clid) -> None: ...
    @property
    def page_id(self): ...
    @page_id.setter
    def page_id(self, page_id) -> None: ...
    def normalize(self): ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
