version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v21.2.3
    entrypoint: cockroach start-single-node --insecure --advertise-addr localhost
    ports:
      - "26257:26257"
    networks:
      - dashboard-api
  setup_cockroachdb:
    image: cockroachdb/cockroach:v21.2.3
    volumes:
      - ./seed_cockroachdb.sql:/tmp/seed_cockroachdb.sql
    entrypoint: |
      sh -c '
        ./cockroach sql --host cockroachdb --insecure -e "CREATE DATABASE vlab"
        ./cockroach sql --host cockroachdb --insecure --database=vlab < /tmp/seed_cockroachdb.sql
      '
    depends_on:
      - cockroachdb
    networks:
      - dashboard-api
networks:
  dashboard-api:
