{
 "title": "Form Status",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "form",
    "query": "select distinct(current_form) as form from states where updated > NOW() - interval '7 days' order by form"
   }
  ]
 },
 "panels": [
  {
   "title": "All Forms - Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = ANY($form)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 4 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 4.8, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 9.6, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 14.399999999999999, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 19.2, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding < 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 8 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND\n  (NOW() - updated) < interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding < 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 4.8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND\n  (NOW() - updated) < interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding < 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 9.6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND\n  (NOW() - updated) < interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding < 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 14.399999999999999, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND\n  (NOW() - updated) < interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding < 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 19.2, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND\n  (NOW() - updated) < interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding > 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 12 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND \n  (NOW() - updated) > interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding > 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 4.8, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND \n  (NOW() - updated) > interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding > 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 9.6, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND \n  (NOW() - updated) > interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding > 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 14.399999999999999, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND \n  (NOW() - updated) > interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding > 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 19.2, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form AND \n  (NOW() - updated) > interval '24 hours'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 16 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 4.8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 9.6, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 14.399999999999999, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 19.2, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  }
 ]
}