{
 "title": "Malaria Incidence",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "form",
    "query": "select distinct(current_form) as form from states where updated > NOW() - interval '7 days' order by form"
   }
  ]
 },
 "panels": [
  {
   "title": "$form",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria,  $__timeGroupAlias(timestamp,$__interval) \nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = ANY($form)\nORDER BY \n  time\n) select time, sum(had_malaria::int) / count(*) as malaria_incidence from t group by time order by time;"
    }
   ]
  },
  {
   "title": "Malaria Incidence",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with y as (with x as (with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria,  $__timeGroupAlias(timestamp,$__interval) \nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = ANY($form)\nORDER BY \n  time\n) select clusterid, time, sum(had_malaria::int) / count(*) as malaria_incidence from t group by time, clusterid order by time)\n select time, AVG(malaria_incidence) as malaria_incidence from x GROUP BY time)\n select time, AVG(malaria_incidence) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_average FROM y ORDER BY time;"
    }
   ]
  },
  {
   "title": "Bednet Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with y as (with x as (with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria,  $__timeGroupAlias(timestamp,$__interval) \nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '1f812d37-a7a5-400d-8a31-145fbb49f577' AND \n  shortcode = ANY($form)\nORDER BY \n  time\n) select clusterid, time, sum(had_malaria::int) / count(*) as malaria_incidence from t group by time, clusterid order by time)\n select time, AVG(malaria_incidence) as malaria_incidence from x GROUP BY time)\n select time, AVG(malaria_incidence) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_average FROM y ORDER BY time;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 22 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select clusterid, sum(had_malaria::int) / count(*) as malaria_incidence, count(*) as count from t group by clusterid;\n\n  "
    }
   ]
  },
  {
   "title": "$form",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select clusterid, sum(had_malaria::int) / count(*) as malaria_incidence, count(*) as count from t group by clusterid;\n\n  "
    }
   ]
  },
  {
   "title": "$form",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select clusterid, sum(had_malaria::int) / count(*) as malaria_incidence, count(*) as count from t group by clusterid;\n\n  "
    }
   ]
  },
  {
   "title": "$form",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = 'हाँ' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '58583e72-7036-4c74-9ebd-179598cba59f' AND \n  shortcode = $form\n) select clusterid, sum(had_malaria::int) / count(*) as malaria_incidence, count(*) as count from t group by clusterid;\n\n  "
    }
   ]
  }
 ]
}