{
 "title": "Response Share Over Time",
 "time": { "from": "now-100d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "form",
    "query": "select distinct(current_form) as form from states where updated > NOW() - interval '7 days' order by form"
   },
   {
    "name": "question_ref",
    "query": "with y as (with t as (select question_ref, shortcode from responses where shortcode = ANY($form)) select question_ref, shortcode from t group by question_ref, shortcode) select question_ref from y group by question_ref having array_agg(shortcode) @> (ARRAY($form)) AND (ARRAY($form)) @> array_agg(shortcode);"
   },
   {
    "name": "response",
    "query": "with t as (select response, count(response) from responses where question_ref = '$question_ref' group by response) select response from t where count > 2;"
   }
  ]
 },
 "panels": [
  {
   "title": "Response percentage per day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = '$response' as had_malaria,  $__timeGroupAlias(timestamp,$__interval) \nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '$question_ref' AND \n  shortcode = ANY($form)\nORDER BY \n  time\n) select time, sum(had_malaria::int) / count(*) as malaria_incidence from t group by time order by time;"
    }
   ]
  },
  {
   "title": "Rolling Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with y as (with x as (with t as (SELECT\n  response, clusterid, response = '$response' as had_malaria,  $__timeGroupAlias(timestamp,$__interval) \nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '$question_ref' AND \n  shortcode = ANY($form)\nORDER BY \n  time\n) select clusterid, time, sum(had_malaria::int) / count(*) as malaria_incidence from t group by time, clusterid order by time)\n select time, AVG(malaria_incidence) as malaria_incidence from x GROUP BY time)\n select time, AVG(malaria_incidence) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_average FROM y ORDER BY time;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 16 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = '$response' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '$question_ref' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 4.8, "y": 16 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = '$response' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '$question_ref' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 9.6, "y": 16 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = '$response' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '$question_ref' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 14.399999999999999, "y": 16 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = '$response' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '$question_ref' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  },
  {
   "title": "$form",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 19.2, "y": 16 },
   "targets": [
    {
     "rawSql": "with t as (SELECT\n  response, clusterid, response = '$response' as had_malaria\nFROM\n  responses\nWHERE\n  $__timeFilter(timestamp) AND \n  question_ref = '$question_ref' AND \n  shortcode = $form\n) select sum(had_malaria::int) / count(*) as malaria_incidence from t;"
    }
   ]
  }
 ]
}