{
 "title": "State Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "select distinct(current_state) from states;"
   }
  ]
 },
 "panels": [
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "repeat": "state",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = $state"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = $state"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = $state"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = $state"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = $state"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as value\nFROM states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = $state"
    }
   ]
  },
  {
   "title": "States",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated,$__interval),\n  current_state,\n  count(*)::INT AS \"value\"\nFROM states\nWHERE\n  $__timeFilter(updated)\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  fb_error_code,\n  count(*)\nFROM\n  states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = 'BLOCKED'\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Blocked Error Messages",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*),\n  state_json->'error'->>'message' as message\nFROM\n  states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = 'BLOCKED'\nGROUP BY 2"
    }
   ]
  },
  {
   "title": "Error Error Messages",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*),\n  state_json->'error'->>'message' as message\nFROM\n  states\nWHERE\n  $__timeFilter(updated) AND \n  current_state = 'ERROR'\nGROUP BY 2"
    }
   ]
  }
 ]
}