env:
  - name: AUTH0_DOMAIN
    value: "https://vlab-pro.us.auth0.com/"
  - name: AUTH0_AUDIENCE
    value: "https://api-pro.vlab/"

# get secret names in vprod
envSecrets:
  - gbv-bot-envs
  - vlab-db-envs
  - vlab-typeform-envs

# shared ingress stuff
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

dashboard:
  replicaCount: 1
  image:
    repository: vlabresearch/vlab-dashboard-api
    tag: latest
    pullPolicy: Always
  resources: {}
  ingress:
    host: vlab-dashboard-api.toixo.vlab.digital


# TODO: change to mapping to allow merging.
cronjobs:
  - name: source-typeform
    schedule: "10 * * * *"
    image:
      repository: "vlabresearch/source-typeform"
      tag: "latest"
      pullPolicy: Always
    env:
      - name: TYPEFORM_BASE_URL
        value: https://api.typeform.com
      - name: TYPEFORM_PAGE_SIZE
        value: "500"
  - name: source-fly
    schedule: "10 * * * *"
    image:
      repository: "vlabresearch/source-fly"
      tag: "latest"
      pullPolicy: Always
    env:
      - name: FLY_BASE_URL
        value: http://gbv-dashboard/api/v1/
      - name: FLY_PAGE_SIZE
        value: "500"
  - name: swoosh
    schedule: "30 * * * *"
    image:
      repository: "vlabresearch/swoosh"
      tag: "latest"
      pullPolicy: Always
  - name: adopt-ads
    schedule: "30 */4 * * *"
    image:
      repository: "vlabresearch/adopt"
      tag: "v0.0.94"
      pullPolicy: Always
    args:
      - python
      - malaria_ads.py
  - name: adopt-recruitment-data
    schedule: "10 */4 * * *"
    image:
      repository: "vlabresearch/adopt"
      tag: "v0.0.94"
      pullPolicy: Always
    args:
      - python
      - malaria_recruitment.py
  - name: adopt-audience
    schedule: "50 */4 * * *"
    image:
      repository: "vlabresearch/adopt"
      tag: "v0.0.94"
      pullPolicy: Always
    args:
      - python
      - malaria_audience.py



# try searching by ref in lit_data, quick hack to optimize this weekend
# figure out a/b
# add tarot
# create remarketing campaign manager


serviceAccount:
  create: true
  annotations: {}
  name: "" # use default


# COMMIT TO COCKROACH OPERATOR???
# cockroachdb:
#   image:
#     tag: v21.2.6
#   statefulset:
#     replicas: 2
#     resources:
#       requests:
#         cpu: 100m
#         memory: 1000Mi
#   conf:
#     cache: 3500Mi
#     max-sql-memory: 3000Mi
#     max-disk-temp-storage: 24GiB
#     budget:
#       maxUnavailable: 1
#   tls:
#     enabled: yes
#     certs:
#       selfSigner:
#         enabled: yes
