{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vlab.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/service: {{ .name }}
    {{ include "vlab.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/service: {{ .name }}
      {{- include "vlab.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/service: {{ .name }}
        {{- include "vlab.selectorLabels" $ | nindent 8 }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          {{- if .args }}
          args:
            {{- toYaml .args | nindent 12 }}
          {{- end}}
          {{- with $.Values.envSecrets }}
          envFrom:
            {{- range .}}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end}}
          env:
            {{- if .env -}}
            {{- toYaml .env | nindent 12 }}
            {{- end }}
            {{- if $.Values.env -}}
            {{- toYaml $.Values.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "vlab.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/service: {{ .name }}
    {{ include "vlab.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/service: {{ .name }}
    {{ include "vlab.selectorLabels" $ | nindent 4 }}


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vlab.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/service: {{ .name }}
    {{ include "vlab.labels" $ | nindent 4 }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .ingress.host }}
      secretName: {{ .name }}-api-cert
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vlab.fullname" $ }}-{{ .name }}
                port:
                  number: 80
---
{{- end }}
