DROP VIEW study_state;
DROP TABLE study_confs;
DROP TABLE recruitment_data_events;
DROP TABLE adopt_reports;
DROP TABLE inference_data;
DROP TABLE inference_data_events;
DROP TABLE studies;
DROP TABLE credentials;
DROP TABLE users;
