{
 "title": "Campaign Optimization",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "campaign",
    "query": "select distinct name from campaigns"
   }
  ]
 },
 "panels": [
  {
   "title": "Config",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH t AS \n     (SELECT row_to_json(json_each_text(conf->0)) AS d \n     FROM (SELECT * \n          FROM campaign_confs \n          JOIN campaigns ON campaignid=id \n          WHERE conf_type = 'opt' AND NAME = '$campaign' \n          ORDER BY campaign_confs.created \n          DESC LIMIT 1)\n     )\nSELECT d->>'key' AS KEY, d->>'value' AS VALUE FROM t;"
    }
   ]
  },
  {
   "title": "Current Average Deviation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH tt AS\n  (WITH t AS\n    (SELECT row_to_json(json_each(details)) d, created\n     FROM (SELECT details, adopt_reports.created\n          FROM adopt_reports\n          JOIN campaigns ON campaignid = campaigns.id\n          WHERE campaigns.NAME = '$campaign'\n          ORDER BY created DESC\n          LIMIT 1))\n  SELECT\n      created,\n      (d->'value'->>'goal')::FLOAT AS goal,\n      (d->'value'->>'respondent_share')::FLOAT AS share\n  FROM t)\nSELECT AVG(ABS(goal - share))*100 AS dif\nFROM tt;"
    }
   ]
  },
  {
   "title": "Average Deviation Over Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH tt AS \n  (WITH t AS \n    (SELECT row_to_json(json_each(details)) d, created \n     FROM (SELECT details, adopt_reports.created FROM adopt_reports JOIN campaigns ON campaignid = campaigns.id WHERE campaigns.NAME = '$campaign')) \n  SELECT \n      created,\n      (d->'value'->>'goal')::FLOAT AS goal,\n      (d->'value'->>'respondent_share')::FLOAT AS share\n  FROM t) \nSELECT $__time(created), AVG(ABS(goal - share))*100 AS dif \nFROM tt \nWHERE\n  $__timeFilter(created)\nGROUP BY created \nORDER BY created;"
    }
   ]
  },
  {
   "title": "Expected Average Deviation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH tt AS\n  (WITH t AS\n    (SELECT row_to_json(json_each(details)) d, created\n     FROM (SELECT details, adopt_reports.created\n          FROM adopt_reports\n          JOIN campaigns ON campaignid = campaigns.id\n          WHERE campaigns.NAME = '$campaign'\n          ORDER BY created DESC\n          LIMIT 1))\n  SELECT\n      created,\n      (d->'value'->>'goal')::FLOAT AS goal,\n      (d->'value'->>'expected_share')::FLOAT AS share\n  FROM t)\nSELECT AVG(ABS(goal - share))*100 AS dif\nFROM tt;"
    }
   ]
  },
  {
   "title": "Deviation Over Time by Stratum",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "\nWITH tt AS\n  (WITH t AS\n    (SELECT row_to_json(json_each(details)) d, created\n     FROM (SELECT details, adopt_reports.created\n          FROM adopt_reports\n          JOIN campaigns ON campaignid = campaigns.id\n          WHERE campaigns.NAME = '$campaign'))\n  SELECT\n      created,\n      d->>'key' AS stratum,\n      (d->'value'->>'goal')::FLOAT AS goal,\n      (d->'value'->>'respondent_share')::FLOAT AS share\n  FROM t)\nSELECT $__time(created), stratum as metric, goal - share as value\nFROM tt\nWHERE\n  $__timeFilter(created)\nORDER BY created;"
    }
   ]
  },
  {
   "title": "Stratum Targets",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH tt AS \n  (WITH t AS \n    (SELECT row_to_json(json_each(details)) d \n    FROM (SELECT details, adopt_reports.created \n          FROM adopt_reports \n          JOIN campaigns ON campaignid = campaigns.id \n          WHERE campaigns.NAME = '$campaign' \n          ORDER BY created DESC \n          LIMIT 1)) \n  SELECT d->>'key' AS stratum, \n  (d->'value'->>'goal')::FLOAT AS goal,\n  (d->'value'->>'expected_share')::FLOAT as expected_share,\n  (d->'value'->>'respondent_share')::FLOAT AS current_share,\n  (d->'value'->>'budget')::FLOAT AS budget\n  FROM t)  \nSELECT *, goal - current_share AS current_gap \nFROM tt \nORDER BY current_gap DESC;"
    }
   ]
  },
  {
   "title": "Current Deviation by Stratum",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH tt AS \n  (WITH t AS \n    (SELECT row_to_json(json_each(details)) d \n    FROM (SELECT details, adopt_reports.created \n          FROM adopt_reports \n          JOIN campaigns ON campaignid = campaigns.id \n          WHERE campaigns.NAME = '$campaign' \n          ORDER BY created DESC \n          LIMIT 1)) \n  SELECT d->>'key' AS stratum, \n  (d->'value'->>'goal')::FLOAT AS goal,\n  (d->'value'->>'respondent_share')::FLOAT AS current_share\n  FROM t)  \nSELECT stratum, current_share - goal  AS current_gap \nFROM tt \nORDER BY current_gap DESC;"
    }
   ]
  }
 ]
}