{
 "title": "Form Status",
 "time": { "from": "now-31d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "form",
    "query": "select distinct(current_form) as form from states where updated > NOW() - interval '7 days' order by form"
   }
  ]
 },
 "panels": [
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Waiting Timeout",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'WAIT_EXTERNAL_EVENT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Not Responding",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'QOUT' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "repeat": "form",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM states\nWHERE\n  $__timeFilter(updated) AND\n  current_state = 'BLOCKED' AND\n  current_form = $form\nORDER BY 1"
    }
   ]
  }
 ]
}