from facebook_business.adobjects.adspixel import AdsPixel as AdsPixel
from facebook_business.adobjects.serverside.event import Event as Event
from facebook_business.adobjects.serverside.event_response import EventResponse as EventResponse
from typing import Any

class EventRequest:
    param_types: Any = ...
    def __init__(self, pixel_id: str=..., events: List[Event]=..., test_event_code: str=...) -> None: ...
    @property
    def events(self): ...
    @events.setter
    def events(self, events: Any) -> None: ...
    @property
    def test_event_code(self): ...
    @test_event_code.setter
    def test_event_code(self, test_event_code: Any) -> None: ...
    def execute(self): ...
    def normalize(self): ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
