from typing import Any

class EventResponse:
    param_types: Any = ...
    def __init__(self, events_received: int=..., messages: List[str]=..., fbtrace_id: str=...) -> None: ...
    @property
    def events_received(self): ...
    @events_received.setter
    def events_received(self, events_received: Any) -> None: ...
    @property
    def messages(self): ...
    @messages.setter
    def messages(self, messages: Any) -> None: ...
    @property
    def fbtrace_id(self): ...
    @fbtrace_id.setter
    def fbtrace_id(self, fbtrace_id: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
