from facebook_business.adobjects.serverside.gender import Gender as Gender
from facebook_business.adobjects.serverside.normalize import Normalize as Normalize
from typing import Any

class UserData:
    param_types: Any = ...
    def __init__(self, email: str=..., phone: str=..., gender: Gender=..., date_of_birth: str=..., last_name: str=..., first_name: str=..., city: str=..., state: str=..., country_code: str=..., zip_code: str=..., external_id: str=..., client_ip_address: str=..., client_user_agent: str=..., fbc: str=..., fbp: str=..., subscription_id: str=..., fb_login_id: str=...) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email: Any) -> None: ...
    @property
    def phone(self): ...
    @phone.setter
    def phone(self, phone: Any) -> None: ...
    @property
    def gender(self): ...
    @gender.setter
    def gender(self, gender: Any) -> None: ...
    @property
    def date_of_birth(self): ...
    @date_of_birth.setter
    def date_of_birth(self, date_of_birth: Any) -> None: ...
    @property
    def last_name(self): ...
    @last_name.setter
    def last_name(self, last_name: Any) -> None: ...
    @property
    def first_name(self): ...
    @first_name.setter
    def first_name(self, first_name: Any) -> None: ...
    @property
    def city(self): ...
    @city.setter
    def city(self, city: Any) -> None: ...
    @property
    def state(self): ...
    @state.setter
    def state(self, state: Any) -> None: ...
    @property
    def country_code(self): ...
    @country_code.setter
    def country_code(self, country_code: Any) -> None: ...
    @property
    def zip_code(self): ...
    @zip_code.setter
    def zip_code(self, zip_code: Any) -> None: ...
    @property
    def external_id(self): ...
    @external_id.setter
    def external_id(self, external_id: Any) -> None: ...
    @property
    def client_ip_address(self): ...
    @client_ip_address.setter
    def client_ip_address(self, client_ip_address: Any) -> None: ...
    @property
    def client_user_agent(self): ...
    @client_user_agent.setter
    def client_user_agent(self, client_user_agent: Any) -> None: ...
    @property
    def fbc(self): ...
    @fbc.setter
    def fbc(self, fbc: Any) -> None: ...
    @property
    def fbp(self): ...
    @fbp.setter
    def fbp(self, fbp: Any) -> None: ...
    @property
    def subscription_id(self): ...
    @subscription_id.setter
    def subscription_id(self, subscription_id: Any) -> None: ...
    @property
    def fb_login_id(self): ...
    @fb_login_id.setter
    def fb_login_id(self, fb_login_id: Any) -> None: ...
    def normalize(self): ...
    def hash_sha_256(self, input: Any): ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
