apiVersion: batch/v1
kind: Job
metadata:
  name: gbv-adopt-update-ads-vlab
  labels:
    app: gbv-adopt-update-ads-vlab
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: gbv-adopt-update-ads
        image: vlabresearch/adopt:v0.0.86
        args:
        - python
        - malaria_ads.py
        resources:
          requests:
            cpu: "10m"
            memory: "50Mi"
        envFrom:
        - secretRef:
            name: gbv-adopt-envs
        env:
        - name: CHATBASE_DATABASE
          value: chatroach
        - name: CHATBASE_USER
          value: adopt
        - name: CHATBASE_PASSWORD
        - name: CHATBASE_HOST
          value: gbv-cockroachdb-public
        - name: CHATBASE_PORT
          value: "26257"
