apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gbv-adopt-update-audiences-vlab
  labels:
    app: gbv-adopt-update-audiences-vlab
spec:
  schedule: 0 7,15,23 * * *
  jobTemplate:
    spec:
      activeDeadlineSeconds: 14400 # 4 hours
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: gbv-adopt-update-audiences
            image: vlabresearch/adopt:v0.0.87
            args:
            - python
            - malaria_audience.py
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
            envFrom:
            - secretRef:
                name: gbv-adopt-envs
            env:
            - name: CHATBASE_DATABASE
              value: chatroach
            - name: CHATBASE_USER
              value: adopt
            - name: CHATBASE_PASSWORD
            - name: CHATBASE_HOST
              value: gbv-cockroachdb-public
            - name: CHATBASE_PORT
              value: "26257"
