from _typeshed import Incomplete
from facebook_business.exceptions import FacebookBadParameterTypeException as FacebookBadParameterTypeException
from facebook_business.utils import api_utils as api_utils

class TypeChecker:
    primitive_types: Incomplete
    def __init__(self, type_check_info, type_check_enum) -> None: ...
    def is_primitive_type(self, type): ...
    def convert_string_to_prim_type(self, primitive_type, value): ...
    def get_type(self, param): ...
    def is_valid_key(self, param): ...
    def is_valid_pair(self, param, value): ...
    def is_type(self, value_type, value, allow_dict_as_obj: bool = True): ...
    def is_type_collection(self, value_type, collection_name): ...
    def get_type_from_collection(self, value_type, collection_name): ...
    def is_list_param(self, param): ...
    def is_map_param(self, param): ...
    def is_file_param(self, param): ...
    def get_typed_value(self, key, value): ...
