from typing import Any, Optional

class ReachFrequencyPredictionMixin:
    def reserve(self, prediction_to_release: Optional[Any] = ..., reach: Optional[Any] = ..., budget: Optional[Any] = ..., impression: Optional[Any] = ...): ...
    def cancel(self): ...
