from _typeshed import Incomplete

class ReachFrequencyPredictionMixin:
    def reserve(self, prediction_to_release: Incomplete | None = None, reach: Incomplete | None = None, budget: Incomplete | None = None, impression: Incomplete | None = None): ...
    def cancel(self): ...
