from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.adaccount import AdAccount as AdAccount
from facebook_business.api import FacebookAdsApi as FacebookAdsApi
from facebook_business.exceptions import FacebookBadObjectError as FacebookBadObjectError
from typing import Any, Optional

class AdImageMixin:
    @classmethod
    def remote_create_from_zip(cls, filename: Any, parent_id: Any, api: Optional[Any] = ...): ...
    def get_node_path(self): ...
    def remote_create(self, batch: Optional[Any] = ..., failure: Optional[Any] = ..., files: Optional[Any] = ..., params: Optional[Any] = ..., success: Optional[Any] = ..., api_version: Optional[Any] = ...): ...
    def get_hash(self): ...
    def remote_read(self, batch: Optional[Any] = ..., failure: Optional[Any] = ..., fields: Optional[Any] = ..., params: Optional[Any] = ..., success: Optional[Any] = ..., api_version: Optional[Any] = ...) -> None: ...
