from facebook_business.exceptions import FacebookBadObjectError as FacebookBadObjectError
from typing import Any, Optional

class CustomAudienceMixin:
    class Schema:
        uid: str = ...
        email_hash: str = ...
        phone_hash: str = ...
        mobile_advertiser_id: str = ...
        class MultiKeySchema:
            extern_id: str = ...
            email: str = ...
            phone: str = ...
            gen: str = ...
            doby: str = ...
            dobm: str = ...
            dobd: str = ...
            ln: str = ...
            fn: str = ...
            fi: str = ...
            ct: str = ...
            st: str = ...
            zip: str = ...
            madid: str = ...
            country: str = ...
            appuid: str = ...
    @classmethod
    def format_params(cls, schema: Any, users: Any, is_raw: bool = ..., app_ids: Optional[Any] = ..., pre_hashed: Optional[Any] = ..., session: Optional[Any] = ...): ...
    @classmethod
    def normalize_key(cls, key_name: Any, key_value: Optional[Any] = ...): ...
    def add_users(self, schema: Any, users: Any, is_raw: bool = ..., app_ids: Optional[Any] = ..., pre_hashed: Optional[Any] = ..., session: Optional[Any] = ...): ...
    def remove_users(self, schema: Any, users: Any, is_raw: bool = ..., app_ids: Optional[Any] = ..., pre_hashed: Optional[Any] = ..., session: Optional[Any] = ...): ...
    def share_audience(self, account_ids: Any): ...
    def unshare_audience(self, account_ids: Any): ...
