import collections
from facebook_business.exceptions import FacebookBadObjectError as FacebookBadObjectError
from facebook_business.typechecker import TypeChecker as TypeChecker
from typing import Any

class AbstractObject(collections.MutableMapping):
    class Field: ...
    def __init__(self) -> None: ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any): ...
    def __eq__(self, other: Any) -> Any: ...
    def __delitem__(self, key: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    def __contains__(self, key: Any): ...
    def __unicode__(self): ...
    @classmethod
    def get_endpoint(cls) -> None: ...
    @classmethod
    def get_default_read_fields(cls): ...
    @classmethod
    def set_default_read_fields(cls, fields: Any) -> None: ...
    def set_data(self, data: Any) -> None: ...
    def export_value(self, data: Any): ...
    def export_data(self): ...
    def export_all_data(self): ...
    @classmethod
    def create_object(cls, api: Any, data: Any, target_class: Any): ...
