import collections as collections_abc
from facebook_business.exceptions import FacebookBadObjectError as FacebookBadObjectError
from facebook_business.typechecker import TypeChecker as TypeChecker

class AbstractObject(collections_abc.MutableMapping):
    class Field: ...
    def __init__(self) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __eq__(self, other): ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __contains__(self, key) -> bool: ...
    def __unicode__(self): ...
    @classmethod
    def get_endpoint(cls) -> None: ...
    @classmethod
    def get_default_read_fields(cls): ...
    @classmethod
    def set_default_read_fields(cls, fields) -> None: ...
    def set_data(self, data) -> None: ...
    def export_value(self, data): ...
    def export_data(self): ...
    def export_all_data(self): ...
    @classmethod
    def create_object(cls, api, data, target_class): ...
