from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdAccountDefaultObjective(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        default_objective_for_user: str = ...
        objective_for_level: str = ...
    class DefaultObjectiveForUser:
        app_installs: str = ...
        brand_awareness: str = ...
        canvas_app_engagement: str = ...
        canvas_app_installs: str = ...
        event_responses: str = ...
        lead_generation: str = ...
        link_clicks: str = ...
        local_awareness: str = ...
        messages: str = ...
        mobile_app_engagement: str = ...
        mobile_app_installs: str = ...
        none: str = ...
        offer_claims: str = ...
        page_likes: str = ...
        post_engagement: str = ...
        product_catalog_sales: str = ...
        video_views: str = ...
        website_conversions: str = ...
    class ObjectiveForLevel:
        app_installs: str = ...
        brand_awareness: str = ...
        canvas_app_engagement: str = ...
        canvas_app_installs: str = ...
        event_responses: str = ...
        lead_generation: str = ...
        link_clicks: str = ...
        local_awareness: str = ...
        messages: str = ...
        mobile_app_engagement: str = ...
        mobile_app_installs: str = ...
        none: str = ...
        offer_claims: str = ...
        page_likes: str = ...
        post_engagement: str = ...
        product_catalog_sales: str = ...
        video_views: str = ...
        website_conversions: str = ...
