from _typeshed import Incomplete
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject

class AdAccountDefaultObjective(AbstractObject):
    def __init__(self, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        default_objective_for_user: str
        objective_for_level: str
    class DefaultObjectiveForUser:
        app_installs: str
        brand_awareness: str
        event_responses: str
        lead_generation: str
        link_clicks: str
        local_awareness: str
        messages: str
        offer_claims: str
        outcome_app_promotion: str
        outcome_awareness: str
        outcome_engagement: str
        outcome_leads: str
        outcome_sales: str
        outcome_traffic: str
        page_likes: str
        post_engagement: str
        product_catalog_sales: str
        reach: str
        store_visits: str
        video_views: str
        website_conversions: str
    class ObjectiveForLevel:
        app_installs: str
        brand_awareness: str
        event_responses: str
        lead_generation: str
        link_clicks: str
        local_awareness: str
        messages: str
        offer_claims: str
        outcome_app_promotion: str
        outcome_awareness: str
        outcome_engagement: str
        outcome_leads: str
        outcome_sales: str
        outcome_traffic: str
        page_likes: str
        post_engagement: str
        product_catalog_sales: str
        reach: str
        store_visits: str
        video_views: str
        website_conversions: str
