from _typeshed import Incomplete
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject

class AdAssetFeedSpec(AbstractObject):
    def __init__(self, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        ad_formats: str
        additional_data: str
        app_product_page_id: str
        asset_customization_rules: str
        autotranslate: str
        bodies: str
        call_to_action_types: str
        call_to_actions: str
        captions: str
        carousels: str
        descriptions: str
        events: str
        groups: str
        images: str
        link_urls: str
        message_extensions: str
        onsite_destinations: str
        optimization_type: str
        promotional_metadata: str
        reasons_to_shop: str
        shops_bundle: str
        titles: str
        upcoming_events: str
        videos: str
    class CallToActionTypes:
        add_to_cart: str
        apply_now: str
        ask_about_services: str
        ask_for_more_info: str
        audio_call: str
        book_a_consultation: str
        book_now: str
        book_travel: str
        buy: str
        buy_now: str
        buy_tickets: str
        buy_via_message: str
        call: str
        call_me: str
        call_now: str
        chat_with_us: str
        confirm: str
        contact: str
        contact_us: str
        donate: str
        donate_now: str
        download: str
        event_rsvp: str
        find_a_group: str
        find_your_groups: str
        follow_news_storyline: str
        follow_page: str
        follow_user: str
        get_a_quote: str
        get_directions: str
        get_offer: str
        get_offer_view: str
        get_promotions: str
        get_quote: str
        get_showtimes: str
        get_started: str
        inquire_now: str
        install_app: str
        install_mobile_app: str
        join_channel: str
        learn_more: str
        like_page: str
        listen_music: str
        listen_now: str
        make_an_appointment: str
        message_page: str
        mobile_download: str
        no_button: str
        open_instant_app: str
        open_link: str
        order_now: str
        pay_to_access: str
        play_game: str
        play_game_on_facebook: str
        purchase_gift_cards: str
        raise_money: str
        record_now: str
        refer_friends: str
        request_time: str
        say_thanks: str
        see_more: str
        sell_now: str
        send_a_gift: str
        send_gift_money: str
        send_updates: str
        share: str
        shop_now: str
        sign_up: str
        sotto_subscribe: str
        start_order: str
        subscribe: str
        swipe_up_product: str
        swipe_up_shop: str
        update_app: str
        use_app: str
        use_mobile_app: str
        video_annotation: str
        video_call: str
        view_product: str
        visit_pages_feed: str
        watch_more: str
        watch_video: str
        whatsapp_message: str
        woodhenge_support: str
