from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdCampaignIssuesInfo(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        error_code: str = ...
        error_message: str = ...
        error_summary: str = ...
        error_type: str = ...
        level: str = ...
