from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdCreativeStaticFallbackSpec(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        call_to_action: str = ...
        description: str = ...
        image_hash: str = ...
        link: str = ...
        message: str = ...
        name: str = ...
