from _typeshed import Incomplete
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject

class AdCreativeLinkDataImageOverlaySpec(AbstractObject):
    def __init__(self, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        custom_text_type: str
        float_with_margin: str
        overlay_template: str
        position: str
        text_font: str
        text_template_tags: str
        text_type: str
        theme_color: str
    class CustomTextType:
        free_shipping: str
        popular: str
    class OverlayTemplate:
        circle_with_text: str
        pill_with_text: str
        triangle_with_text: str
    class Position:
        bottom_left: str
        bottom_right: str
        top_left: str
        top_right: str
    class TextFont:
        droid_serif_regular: str
        dynads_hybrid_bold: str
        lato_regular: str
        noto_sans_regular: str
        nunito_sans_bold: str
        open_sans_bold: str
        open_sans_condensed_bold: str
        pt_serif_bold: str
        roboto_condensed_regular: str
        roboto_medium: str
    class TextType:
        automated_personalize: str
        custom: str
        disclaimer: str
        from_price: str
        guest_rating: str
        percentage_off: str
        price: str
        star_rating: str
        strikethrough_price: str
        sustainable: str
    class ThemeColor:
        background_000000_text_ffffff: str
        background_0090ff_text_ffffff: str
        background_00af4c_text_ffffff: str
        background_595959_text_ffffff: str
        background_755dde_text_ffffff: str
        background_e50900_text_ffffff: str
        background_f23474_text_ffffff: str
        background_f78400_text_ffffff: str
        background_ffffff_text_000000: str
        background_ffffff_text_007ad0: str
        background_ffffff_text_009c2a: str
        background_ffffff_text_646464: str
        background_ffffff_text_755dde: str
        background_ffffff_text_c91b00: str
        background_ffffff_text_f23474: str
        background_ffffff_text_f78400: str
