from _typeshed import Incomplete
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject

class AdCreativeLinkDataCallToAction(AbstractObject):
    def __init__(self, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        type: str
        value: str
    class Type:
        add_to_cart: str
        apply_now: str
        audio_call: str
        book_now: str
        book_travel: str
        buy: str
        buy_now: str
        buy_tickets: str
        call: str
        call_me: str
        call_now: str
        confirm: str
        contact: str
        contact_us: str
        donate: str
        donate_now: str
        download: str
        event_rsvp: str
        find_a_group: str
        find_your_groups: str
        follow_news_storyline: str
        follow_page: str
        follow_user: str
        get_directions: str
        get_offer: str
        get_offer_view: str
        get_promotions: str
        get_quote: str
        get_showtimes: str
        get_started: str
        inquire_now: str
        install_app: str
        install_mobile_app: str
        learn_more: str
        like_page: str
        listen_music: str
        listen_now: str
        message_page: str
        mobile_download: str
        no_button: str
        open_instant_app: str
        open_link: str
        order_now: str
        pay_to_access: str
        play_game: str
        play_game_on_facebook: str
        purchase_gift_cards: str
        raise_money: str
        record_now: str
        refer_friends: str
        request_time: str
        say_thanks: str
        see_more: str
        sell_now: str
        send_a_gift: str
        send_gift_money: str
        send_updates: str
        share: str
        shop_now: str
        sign_up: str
        sotto_subscribe: str
        start_order: str
        subscribe: str
        swipe_up_product: str
        swipe_up_shop: str
        update_app: str
        use_app: str
        use_mobile_app: str
        video_annotation: str
        video_call: str
        visit_pages_feed: str
        watch_more: str
        watch_video: str
        whatsapp_message: str
        woodhenge_support: str
