from _typeshed import Incomplete
from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.mixins import HasAdLabels as HasAdLabels
from facebook_business.typechecker import TypeChecker as TypeChecker

class AdCreative(AbstractCrudObject, HasAdLabels):
    def __init__(self, fbid: Incomplete | None = None, parent_id: Incomplete | None = None, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        account_id: str
        actor_id: str
        adlabels: str
        applink_treatment: str
        asset_feed_spec: str
        authorization_category: str
        auto_update: str
        body: str
        branded_content: str
        branded_content_sponsor_page_id: str
        bundle_folder_id: str
        call_to_action_type: str
        categorization_criteria: str
        category_media_source: str
        collaborative_ads_lsb_image_bank_id: str
        contextual_multi_ads: str
        creative_sourcing_spec: str
        degrees_of_freedom_spec: str
        destination_set_id: str
        dynamic_ad_voice: str
        effective_authorization_category: str
        effective_instagram_media_id: str
        effective_instagram_story_id: str
        effective_object_story_id: str
        enable_direct_install: str
        enable_launch_instant_app: str
        facebook_branded_content: str
        id: str
        image_crops: str
        image_hash: str
        image_url: str
        instagram_actor_id: str
        instagram_branded_content: str
        instagram_permalink_url: str
        instagram_story_id: str
        instagram_user_id: str
        interactive_components_spec: str
        link_deep_link_url: str
        link_destination_display_url: str
        link_og_id: str
        link_url: str
        name: str
        object_id: str
        object_store_url: str
        object_story_id: str
        object_story_spec: str
        object_type: str
        object_url: str
        omnichannel_link_spec: str
        page_welcome_message: str
        photo_album_source_object_story_id: str
        place_page_set_id: str
        platform_customizations: str
        playable_asset_id: str
        portrait_customizations: str
        product_set_id: str
        recommender_settings: str
        source_instagram_media_id: str
        status: str
        template_url: str
        template_url_spec: str
        thumbnail_id: str
        thumbnail_url: str
        title: str
        url_tags: str
        use_page_actor_override: str
        video_id: str
        call_to_action: str
        image_file: str
        is_dco_internal: str
    class CallToActionType:
        add_to_cart: str
        apply_now: str
        ask_about_services: str
        ask_for_more_info: str
        audio_call: str
        book_a_consultation: str
        book_now: str
        book_travel: str
        buy: str
        buy_now: str
        buy_tickets: str
        buy_via_message: str
        call: str
        call_me: str
        call_now: str
        chat_with_us: str
        confirm: str
        contact: str
        contact_us: str
        donate: str
        donate_now: str
        download: str
        event_rsvp: str
        find_a_group: str
        find_your_groups: str
        follow_news_storyline: str
        follow_page: str
        follow_user: str
        get_a_quote: str
        get_directions: str
        get_offer: str
        get_offer_view: str
        get_promotions: str
        get_quote: str
        get_showtimes: str
        get_started: str
        inquire_now: str
        install_app: str
        install_mobile_app: str
        join_channel: str
        learn_more: str
        like_page: str
        listen_music: str
        listen_now: str
        make_an_appointment: str
        message_page: str
        mobile_download: str
        no_button: str
        open_instant_app: str
        open_link: str
        order_now: str
        pay_to_access: str
        play_game: str
        play_game_on_facebook: str
        purchase_gift_cards: str
        raise_money: str
        record_now: str
        refer_friends: str
        request_time: str
        say_thanks: str
        see_more: str
        sell_now: str
        send_a_gift: str
        send_gift_money: str
        send_updates: str
        share: str
        shop_now: str
        sign_up: str
        sotto_subscribe: str
        start_order: str
        subscribe: str
        swipe_up_product: str
        swipe_up_shop: str
        update_app: str
        use_app: str
        use_mobile_app: str
        video_annotation: str
        video_call: str
        view_product: str
        visit_pages_feed: str
        watch_more: str
        watch_video: str
        whatsapp_message: str
        woodhenge_support: str
    class ObjectType:
        application: str
        domain: str
        event: str
        invalid: str
        offer: str
        page: str
        photo: str
        post_deleted: str
        privacy_check_fail: str
        share: str
        status: str
        store_item: str
        video: str
    class Status:
        active: str
        deleted: str
        in_process: str
        with_issues: str
    class ApplinkTreatment:
        automatic: str
        deeplink_with_appstore_fallback: str
        deeplink_with_web_fallback: str
        web_only: str
    class AuthorizationCategory:
        none: str
        political: str
        political_with_digitally_created_media: str
    class CategorizationCriteria:
        brand: str
        category: str
        product_type: str
    class CategoryMediaSource:
        category: str
        mixed: str
        products_collage: str
        products_slideshow: str
    class DynamicAdVoice:
        dynamic: str
        story_owner: str
    class Operator:
        all: str
        any: str
    @classmethod
    def get_endpoint(cls): ...
    def api_create(self, parent_id, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def api_delete(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def api_get(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def api_update(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def create_ad_label(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def get_creative_insights(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def get_previews(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
