from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdKeywords(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        brands: str = ...
        product_categories: str = ...
        product_names: str = ...
        search_terms: str = ...
