from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdPlacePageSetMetadata(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        audience: str = ...
        custom: str = ...
        extra_data: str = ...
        fixed_radius: str = ...
