from _typeshed import Incomplete
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject

class AdPromotedObject(AbstractObject):
    def __init__(self, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        application_id: str
        conversion_goal_id: str
        custom_conversion_id: str
        custom_event_str: str
        custom_event_type: str
        event_id: str
        fundraiser_campaign_id: str
        mcme_conversion_id: str
        object_store_url: str
        offer_id: str
        offline_conversion_data_set_id: str
        offsite_conversion_event_id: str
        omnichannel_object: str
        page_id: str
        pixel_aggregation_rule: str
        pixel_id: str
        pixel_rule: str
        place_page_set: str
        place_page_set_id: str
        product_catalog_id: str
        product_item_id: str
        product_set: str
        product_set_id: str
        retention_days: str
        whatsapp_phone_number: str
    class CustomEventType:
        achievement_unlocked: str
        add_payment_info: str
        add_to_cart: str
        add_to_wishlist: str
        ad_impression: str
        complete_registration: str
        contact: str
        content_view: str
        customize_product: str
        d2_retention: str
        d7_retention: str
        donate: str
        find_location: str
        initiated_checkout: str
        lead: str
        level_achieved: str
        listing_interaction: str
        messaging_conversation_started_7d: str
        other: str
        purchase: str
        rate: str
        schedule: str
        search: str
        service_booking_request: str
        spent_credits: str
        start_trial: str
        submit_application: str
        subscribe: str
        tutorial_completion: str
