from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.helpers.adpreviewmixin import AdPreviewMixin as AdPreviewMixin
from typing import Any, Optional

class AdPreview(AdPreviewMixin, AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        body: str = ...
    class AdFormat:
        audience_network_instream_video: str = ...
        audience_network_instream_video_mobile: str = ...
        audience_network_outstream_video: str = ...
        audience_network_rewarded_video: str = ...
        desktop_feed_standard: str = ...
        facebook_story_mobile: str = ...
        instagram_explore_contextual: str = ...
        instagram_explore_immersive: str = ...
        instagram_standard: str = ...
        instagram_story: str = ...
        instant_article_recirculation_ad: str = ...
        instant_article_standard: str = ...
        instream_video_desktop: str = ...
        instream_video_image: str = ...
        instream_video_mobile: str = ...
        job_browser_desktop: str = ...
        job_browser_mobile: str = ...
        marketplace_mobile: str = ...
        messenger_mobile_inbox_media: str = ...
        messenger_mobile_story_media: str = ...
        mobile_banner: str = ...
        mobile_feed_basic: str = ...
        mobile_feed_standard: str = ...
        mobile_fullwidth: str = ...
        mobile_interstitial: str = ...
        mobile_medium_rectangle: str = ...
        mobile_native: str = ...
        right_column_standard: str = ...
        suggested_video_desktop: str = ...
        suggested_video_mobile: str = ...
        watch_feed_home: str = ...
        watch_feed_mobile: str = ...
    class RenderType:
        fallback: str = ...
    @classmethod
    def get_endpoint(cls): ...
