from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdRuleHistory(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        evaluation_spec: str = ...
        exception_code: str = ...
        exception_message: str = ...
        execution_spec: str = ...
        is_manual: str = ...
        results: str = ...
        schedule_spec: str = ...
        timestamp: str = ...
    class Action:
        budget_not_redistributed: str = ...
        changed_bid: str = ...
        changed_budget: str = ...
        email: str = ...
        endpoint_pinged: str = ...
        error: str = ...
        facebook_notification_sent: str = ...
        message_sent: str = ...
        not_changed: str = ...
        paused: str = ...
        unpaused: str = ...
