from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdRuleExecutionSpec(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        execution_options: str = ...
        execution_type: str = ...
    class ExecutionType:
        change_bid: str = ...
        change_budget: str = ...
        change_campaign_budget: str = ...
        notification: str = ...
        pause: str = ...
        ping_endpoint: str = ...
        rebalance_budget: str = ...
        rotate: str = ...
        unpause: str = ...
