from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class BilledAmountDetails(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        currency: str = ...
        net_amount: str = ...
        tax_amount: str = ...
        total_amount: str = ...
