from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class CampaignGroupBrandConfiguration(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        brand_product_name: str = ...
        locale: str = ...
        vertical: str = ...
