from _typeshed import Incomplete
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject

class CatalogSubVerticalList(AbstractObject):
    def __init__(self, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        appliances: str
        baby_feeding: str
        baby_transport: str
        beauty: str
        bedding: str
        cameras: str
        cameras_and_photos: str
        cell_phones_and_smart_watches: str
        cleaning_supplies: str
        clo_offer: str
        clothing: str
        clothing_accessories: str
        computer_components: str
        computers_and_tablets: str
        computers_laptops_and_tablets: str
        diapering_and_potty_training: str
        digital_product_offer: str
        electronic_accessories_and_cables: str
        electronics_accessories: str
        furniture: str
        health: str
        home: str
        home_goods: str
        household_and_cleaning_supplies: str
        jewelry: str
        large_appliances: str
        local_service_business_item: str
        local_service_business_restaurant: str
        loyalty_offer: str
        meetup_space: str
        nursery: str
        printers_and_scanners: str
        printers_scanners_and_fax_machines: str
        product_discount: str
        projectors: str
        shoes: str
        shoes_and_footwear: str
        software: str
        televisions_and_monitors: str
        test_child_sub_vertical: str
        test_grand_child_sub_vertical: str
        test_sub_vertical: str
        test_sub_vertical_alias: str
        test_sub_vertical_data_object: str
        third_party_electronics: str
        third_party_toys_and_games: str
        toys: str
        toys_and_games: str
        tvs_and_monitors: str
        vehicle_manufacturer: str
        video_game_consoles_and_video_games: str
        video_games_and_consoles: str
        video_projectors: str
        watches: str
