from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from typing import Any, Optional

class ClickTrackingTag(AbstractCrudObject):
    class Field:
        add_template_param: str = ...
        ad_id: str = ...
        id: str = ...
        url: str = ...
    @classmethod
    def get_endpoint(cls): ...
    def get_node_path(self): ...
    def remote_delete(self, params: Optional[Any] = ...): ...
