from _typeshed import Incomplete
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject

class CustomAudienceDataSource(AbstractObject):
    def __init__(self, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        creation_params: str
        sub_type: str
        type: str
    class SubType:
        anything: str
        app_users: str
        ar_effects_events: str
        ar_experience_events: str
        campaign_conversions: str
        combination_custom_audience_users: str
        constant_contacts_email_hashes: str
        contact_importer: str
        conversion_pixel_hits: str
        copy_paste_email_hashes: str
        custom_audience_users: str
        custom_data_targeting: str
        data_file: str
        dynamic_rule: str
        engagement_event_users: str
        expanded_audience: str
        external_ids: str
        external_ids_mix: str
        facebook_wifi_events: str
        fb_event_signals: str
        fb_pixel_hits: str
        hashes: str
        hashes_or_user_ids: str
        household_expansion: str
        ig_business_events: str
        ig_promoted_post: str
        instant_article_events: str
        lookalike_platform: str
        mail_chimp_email_hashes: str
        messenger_onsite_subscription: str
        mobile_advertiser_ids: str
        mobile_app_combination_events: str
        mobile_app_custom_audience_users: str
        mobile_app_events: str
        multicountry_combination: str
        multi_data_events: str
        multi_event_source: str
        multi_hashes: str
        nothing: str
        offline_event_users: str
        page_fans: str
        page_smart_audience: str
        partner_category_users: str
        place_visits: str
        platform: str
        platform_users: str
        seed_list: str
        signal_source: str
        smart_audience: str
        store_visit_events: str
        subscriber_list: str
        s_expr: str
        tokens: str
        user_ids: str
        video_events: str
        video_event_users: str
        web_pixel_combination_events: str
        web_pixel_hits: str
        web_pixel_hits_custom_audience_users: str
    class Type:
        contact_importer: str
        copy_paste: str
        event_based: str
        file_imported: str
        household_audience: str
        seed_based: str
        third_party_imported: str
        unknown: str
