from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class DynamicPostChildAttachment(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        description: str = ...
        image_url: str = ...
        link: str = ...
        place_id: str = ...
        product_id: str = ...
        title: str = ...
