from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class FAMEExportConfig(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        can_edit: str = ...
        column_id: str = ...
        display_name: str = ...
        format: str = ...
