from _typeshed import Incomplete
from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker

class ImageCopyright(AbstractCrudObject):
    def __init__(self, fbid: Incomplete | None = None, parent_id: Incomplete | None = None, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        artist: str
        copyright_monitoring_status: str
        creation_time: str
        creator: str
        custom_id: str
        description: str
        filename: str
        id: str
        image: str
        matches_count: str
        original_content_creation_date: str
        ownership_countries: str
        tags: str
        title: str
        update_time: str
    class GeoOwnership:
        ad: str
        ae: str
        af: str
        ag: str
        ai: str
        al: str
        am: str
        an: str
        ao: str
        aq: str
        ar: str
        value_as: str
        at: str
        au: str
        aw: str
        ax: str
        az: str
        ba: str
        bb: str
        bd: str
        be: str
        bf: str
        bg: str
        bh: str
        bi: str
        bj: str
        bl: str
        bm: str
        bn: str
        bo: str
        bq: str
        br: str
        bs: str
        bt: str
        bv: str
        bw: str
        by: str
        bz: str
        ca: str
        cc: str
        cd: str
        cf: str
        cg: str
        ch: str
        ci: str
        ck: str
        cl: str
        cm: str
        cn: str
        co: str
        cr: str
        cu: str
        cv: str
        cw: str
        cx: str
        cy: str
        cz: str
        de: str
        dj: str
        dk: str
        dm: str
        do: str
        dz: str
        ec: str
        ee: str
        eg: str
        eh: str
        er: str
        es: str
        et: str
        fi: str
        fj: str
        fk: str
        fm: str
        fo: str
        fr: str
        ga: str
        gb: str
        gd: str
        ge: str
        gf: str
        gg: str
        gh: str
        gi: str
        gl: str
        gm: str
        gn: str
        gp: str
        gq: str
        gr: str
        gs: str
        gt: str
        gu: str
        gw: str
        gy: str
        hk: str
        hm: str
        hn: str
        hr: str
        ht: str
        hu: str
        id: str
        ie: str
        il: str
        im: str
        value_in: str
        io: str
        iq: str
        ir: str
        value_is: str
        it: str
        je: str
        jm: str
        jo: str
        jp: str
        ke: str
        kg: str
        kh: str
        ki: str
        km: str
        kn: str
        kp: str
        kr: str
        kw: str
        ky: str
        kz: str
        la: str
        lb: str
        lc: str
        li: str
        lk: str
        lr: str
        ls: str
        lt: str
        lu: str
        lv: str
        ly: str
        ma: str
        mc: str
        md: str
        me: str
        mf: str
        mg: str
        mh: str
        mk: str
        ml: str
        mm: str
        mn: str
        mo: str
        mp: str
        mq: str
        mr: str
        ms: str
        mt: str
        mu: str
        mv: str
        mw: str
        mx: str
        my: str
        mz: str
        na: str
        nc: str
        ne: str
        nf: str
        ng: str
        ni: str
        nl: str
        no: str
        np: str
        nr: str
        nu: str
        nz: str
        om: str
        pa: str
        pe: str
        pf: str
        pg: str
        ph: str
        pk: str
        pl: str
        pm: str
        pn: str
        pr: str
        ps: str
        pt: str
        pw: str
        py: str
        qa: str
        re: str
        ro: str
        rs: str
        ru: str
        rw: str
        sa: str
        sb: str
        sc: str
        sd: str
        se: str
        sg: str
        sh: str
        si: str
        sj: str
        sk: str
        sl: str
        sm: str
        sn: str
        so: str
        sr: str
        ss: str
        st: str
        sv: str
        sx: str
        sy: str
        sz: str
        tc: str
        td: str
        tf: str
        tg: str
        th: str
        tj: str
        tk: str
        tl: str
        tm: str
        tn: str
        to: str
        tp: str
        tr: str
        tt: str
        tv: str
        tw: str
        tz: str
        ua: str
        ug: str
        um: str
        us: str
        uy: str
        uz: str
        va: str
        vc: str
        ve: str
        vg: str
        vi: str
        vn: str
        vu: str
        wf: str
        ws: str
        xk: str
        ye: str
        yt: str
        za: str
        zm: str
        zw: str
    def api_get(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def api_update(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
