from _typeshed import Incomplete
from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker

class InsightsResult(AbstractCrudObject):
    def __init__(self, fbid: Incomplete | None = None, parent_id: Incomplete | None = None, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        description: str
        description_from_api_doc: str
        id: str
        name: str
        period: str
        title: str
        values: str
    class DatePreset:
        data_maximum: str
        last_14d: str
        last_28d: str
        last_30d: str
        last_3d: str
        last_7d: str
        last_90d: str
        last_month: str
        last_quarter: str
        last_week_mon_sun: str
        last_week_sun_sat: str
        last_year: str
        maximum: str
        this_month: str
        this_quarter: str
        this_week_mon_today: str
        this_week_sun_today: str
        this_year: str
        today: str
        yesterday: str
    class Period:
        day: str
        days_28: str
        lifetime: str
        month: str
        total_over_range: str
        week: str
    class Metric:
        blue_reels_play_count: str
        creator_monetization_qualified_views: str
        fb_media_matching_copyright_comment_count: str
        fb_media_matching_copyright_daily_comment_count: str
        fb_media_matching_copyright_daily_like_count: str
        fb_media_matching_copyright_daily_post_impressions: str
        fb_media_matching_copyright_daily_post_impressions_by_age_bucket_and_gender: str
        fb_media_matching_copyright_daily_post_impressions_by_country: str
        fb_media_matching_copyright_daily_post_impressions_by_locale: str
        fb_media_matching_copyright_daily_post_impressions_by_matching_post_id: str
        fb_media_matching_copyright_daily_post_impressions_by_matching_post_owner_id: str
        fb_media_matching_copyright_daily_post_reactions_anger_count: str
        fb_media_matching_copyright_daily_post_reactions_haha_count: str
        fb_media_matching_copyright_daily_post_reactions_like_count: str
        fb_media_matching_copyright_daily_post_reactions_love_count: str
        fb_media_matching_copyright_daily_post_reactions_sorry_count: str
        fb_media_matching_copyright_daily_post_reactions_wow_count: str
        fb_media_matching_copyright_daily_post_share_count: str
        fb_media_matching_copyright_like_count: str
        fb_media_matching_copyright_post_impressions: str
        fb_media_matching_copyright_post_impressions_by_age_bucket_and_gender: str
        fb_media_matching_copyright_post_impressions_by_country: str
        fb_media_matching_copyright_post_impressions_by_locale: str
        fb_media_matching_copyright_post_impressions_by_matching_post_id: str
        fb_media_matching_copyright_post_impressions_by_matching_post_owner_id: str
        fb_media_matching_copyright_post_reactions_anger_count: str
        fb_media_matching_copyright_post_reactions_haha_count: str
        fb_media_matching_copyright_post_reactions_like_count: str
        fb_media_matching_copyright_post_reactions_love_count: str
        fb_media_matching_copyright_post_reactions_sorry_count: str
        fb_media_matching_copyright_post_reactions_wow_count: str
        fb_media_matching_copyright_post_share_count: str
        fb_reels_replay_count: str
        fb_reels_total_plays: str
        has_total_video_views_by_publisher_platform_type: str
        post_impressions_unique: str
        post_video_avg_time_watched: str
        post_video_followers: str
        post_video_likes_by_reaction_type: str
        post_video_retention_graph: str
        post_video_social_actions: str
        post_video_view_time: str
        rights_manager_matching_copyright_matching_page_or_profile_view_count: str
        rights_manager_matching_copyright_matching_video_view_count: str
        rights_manager_matching_copyright_video_view_count: str
        rights_manager_matching_copyright_video_view_count_60s: str
        rights_manager_matching_copyright_video_view_count_60s_by_age_bucket_and_gender: str
        rights_manager_matching_copyright_video_view_count_60s_by_country_id: str
        rights_manager_matching_copyright_video_view_count_60s_by_locale: str
        total_audio_only_product_listen_count: str
        total_video_10s_views: str
        total_video_10s_views_auto_played: str
        total_video_10s_views_clicked_to_play: str
        total_video_10s_views_organic: str
        total_video_10s_views_paid: str
        total_video_10s_views_sound_on: str
        total_video_10s_views_unique: str
        total_video_15s_views: str
        total_video_30s_views: str
        total_video_30s_views_auto_played: str
        total_video_30s_views_clicked_to_play: str
        total_video_30s_views_organic: str
        total_video_30s_views_paid: str
        total_video_30s_views_unique: str
        total_video_60s_excludes_shorter_views: str
        total_video_60s_excludes_shorter_views_by_age_bucket_and_gender: str
        total_video_60s_excludes_shorter_views_by_distribution_source: str
        total_video_60s_excludes_shorter_views_by_growth_accounting_bucket: str
        total_video_60s_excludes_shorter_views_by_growth_accounting_bucket_and_time_since_creation_bucket: str
        total_video_60s_excludes_shorter_views_by_is_60s_returning_viewer: str
        total_video_60s_excludes_shorter_views_by_is_60s_returning_viewer_and_time_since_creation_bucket: str
        total_video_60s_excludes_shorter_views_live: str
        total_video_60s_excludes_shorter_views_unique: str
        total_video_60s_excludes_shorter_views_unique_by_age_bucket_and_gender: str
        total_video_60s_excludes_shorter_views_unique_by_growth_accounting_bucket: str
        total_video_60s_excludes_shorter_views_unique_by_growth_accounting_bucket_and_time_since_creation_bucket: str
        total_video_60s_excludes_shorter_views_unique_by_is_60s_returning_viewer: str
        total_video_60s_excludes_shorter_views_unique_by_is_60s_returning_viewer_and_time_since_creation_bucket: str
        total_video_ad_break_ad_cpm: str
        total_video_ad_break_ad_impressions: str
        total_video_ad_break_earnings: str
        total_video_ad_break_earnings_with_subsidy: str
        total_video_ad_impressions_by_monetization_type: str
        total_video_avg_time_watched: str
        total_video_avg_time_watched_by_distribution_source: str
        total_video_avg_time_watched_by_is_60s_returning_viewer: str
        total_video_avg_time_watched_by_time_since_creation_bucket: str
        total_video_avg_time_watched_followers: str
        total_video_avg_time_watched_live: str
        total_video_comment_sentiment: str
        total_video_comment_sentiment_by_factors: str
        total_video_complete_views: str
        total_video_complete_views_auto_played: str
        total_video_complete_views_clicked_to_play: str
        total_video_complete_views_organic: str
        total_video_complete_views_organic_unique: str
        total_video_complete_views_paid: str
        total_video_complete_views_paid_unique: str
        total_video_complete_views_unique: str
        total_video_consumption_rate: str
        total_video_followers_unique: str
        total_video_growth_score: str
        total_video_growth_score_by_factors: str
        total_video_impressions: str
        total_video_impressions_fan: str
        total_video_impressions_fan_paid: str
        total_video_impressions_fan_paid_unique: str
        total_video_impressions_fan_unique: str
        total_video_impressions_organic: str
        total_video_impressions_organic_unique: str
        total_video_impressions_paid: str
        total_video_impressions_paid_unique: str
        total_video_impressions_unique: str
        total_video_impressions_viral: str
        total_video_impressions_viral_unique: str
        total_video_imps_count_unique_by_age_bucket: str
        total_video_imps_count_unique_by_age_bucket_and_gender: str
        total_video_imps_count_unique_by_gender: str
        total_video_likes_by_reaction_type: str
        total_video_negative_feedback: str
        total_video_net_followers: str
        total_video_net_followers_unique: str
        total_video_net_followers_unique_by_time_since_creation_bucket: str
        total_video_play_count: str
        total_video_play_count_by_is_60s_returning_viewer_and_time_since_creation_bucket: str
        total_video_play_count_by_time_since_creation_bucket: str
        total_video_reactions_by_type_total: str
        total_video_relative_retention_graph: str
        total_video_retention_graph: str
        total_video_retention_graph_15s: str
        total_video_retention_graph_15s_followers: str
        total_video_retention_graph_15s_newsfeed: str
        total_video_retention_graph_15s_recommended: str
        total_video_retention_graph_15s_shares: str
        total_video_retention_graph_15s_watch: str
        total_video_retention_graph_autoplayed: str
        total_video_retention_graph_clicked_to_play: str
        total_video_retention_graph_gender_female: str
        total_video_retention_graph_gender_male: str
        total_video_social_actions: str
        total_video_social_actions_comment_by_distribution_type: str
        total_video_social_actions_count_unique: str
        total_video_social_actions_count_unique_by_age_bucket: str
        total_video_social_actions_count_unique_by_age_bucket_and_gender: str
        total_video_social_actions_count_unique_by_gender: str
        total_video_social_actions_reaction_by_distribution_type: str
        total_video_stories_by_action_type: str
        total_video_unfollowers: str
        total_video_unfollowers_unique: str
        total_video_view_count_unique_by_age_bucket: str
        total_video_view_count_unique_by_age_bucket_and_gender: str
        total_video_view_count_unique_by_gender: str
        total_video_view_time_by_age_bucket_and_gender: str
        total_video_view_time_by_country_id: str
        total_video_view_time_by_distribution_source: str
        total_video_view_time_by_distribution_type: str
        total_video_view_time_by_is_60s_returning_viewer_and_time_since_creation_bucket: str
        total_video_view_time_by_region_id: str
        total_video_view_time_by_time_since_creation_bucket: str
        total_video_view_total_time: str
        total_video_view_total_time_by_is_60s_returning_viewer: str
        total_video_view_total_time_by_paid_non_paid: str
        total_video_view_total_time_live: str
        total_video_view_total_time_organic: str
        total_video_view_total_time_paid: str
        total_video_view_total_time_vod: str
        total_video_views: str
        total_video_views_autoplayed: str
        total_video_views_by_age_bucket_and_gender: str
        total_video_views_by_country_id: str
        total_video_views_by_distribution_type: str
        total_video_views_by_paid_non_paid: str
        total_video_views_by_region_id: str
        total_video_views_by_region_id_proper: str
        total_video_views_clicked_to_play: str
        total_video_views_gender_female: str
        total_video_views_gender_female_live: str
        total_video_views_gender_male: str
        total_video_views_gender_male_live: str
        total_video_views_live: str
        total_video_views_live_autoplayed: str
        total_video_views_live_clicked_to_play: str
        total_video_views_organic: str
        total_video_views_organic_unique: str
        total_video_views_paid: str
        total_video_views_paid_unique: str
        total_video_views_sound_on: str
        total_video_views_unique: str
        total_video_views_vod: str
        video_asset_60s_video_view_total_count_by_is_monetizable: str
