from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker
from typing import Any, Optional

class InstagramInsightsResult(AbstractCrudObject):
    def __init__(self, fbid: Optional[Any] = ..., parent_id: Optional[Any] = ..., api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        description: str = ...
        id: str = ...
        name: str = ...
        period: str = ...
        title: str = ...
        values: str = ...
    class Metric:
        carousel_album_engagement: str = ...
        carousel_album_impressions: str = ...
        carousel_album_reach: str = ...
        carousel_album_saved: str = ...
        carousel_album_video_views: str = ...
        engagement: str = ...
        exits: str = ...
        impressions: str = ...
        reach: str = ...
        replies: str = ...
        saved: str = ...
        taps_back: str = ...
        taps_forward: str = ...
        video_views: str = ...
    class Period:
        day: str = ...
        days_28: str = ...
        lifetime: str = ...
        month: str = ...
        week: str = ...
