from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class InstantArticleInsightsQueryResult(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        breakdowns: str = ...
        name: str = ...
        time: str = ...
        value: str = ...
    class Breakdown:
        age: str = ...
        country: str = ...
        gender: str = ...
        gender_and_age: str = ...
        is_organic: str = ...
        is_shared_by_ia_owner: str = ...
        no_breakdown: str = ...
        platform: str = ...
        region: str = ...
    class Period:
        day: str = ...
        days_28: str = ...
        lifetime: str = ...
        month: str = ...
        week: str = ...
