from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class LeadGenPostSubmissionCheckResult(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        api_call_result: str = ...
        api_error_message: str = ...
        shown_thank_you_page: str = ...
