from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class LeadGenAppointmentBookingInfo(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        advertiser_timezone_offset: str = ...
        appointment_durations: str = ...
        appointment_slots_by_day: str = ...
