from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class PagePaymentOptions(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        amex: str = ...
        cash_only: str = ...
        discover: str = ...
        mastercard: str = ...
        visa: str = ...
