from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class Permission(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        permission: str = ...
        status: str = ...
    class Status:
        declined: str = ...
        expired: str = ...
        granted: str = ...
