from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class ProductItemCommerceInsights(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        message_sends: str = ...
        organic_impressions: str = ...
        paid_impressions: str = ...
