from _typeshed import Incomplete
from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker

class ProductItem(AbstractCrudObject):
    def __init__(self, fbid: Incomplete | None = None, parent_id: Incomplete | None = None, api: Incomplete | None = None) -> None: ...
    class Field(AbstractObject.Field):
        additional_image_cdn_urls: str
        additional_image_urls: str
        additional_variant_attributes: str
        age_group: str
        applinks: str
        availability: str
        brand: str
        capability_to_review_status: str
        category: str
        category_specific_fields: str
        color: str
        commerce_insights: str
        condition: str
        currency: str
        custom_data: str
        custom_label_0: str
        custom_label_1: str
        custom_label_2: str
        custom_label_3: str
        custom_label_4: str
        custom_number_0: str
        custom_number_1: str
        custom_number_2: str
        custom_number_3: str
        custom_number_4: str
        description: str
        errors: str
        expiration_date: str
        fb_product_category: str
        gender: str
        gtin: str
        id: str
        image_cdn_urls: str
        image_fetch_status: str
        image_url: str
        images: str
        importer_address: str
        importer_name: str
        invalidation_errors: str
        inventory: str
        manufacturer_info: str
        manufacturer_part_number: str
        marked_for_product_launch: str
        material: str
        mobile_link: str
        name: str
        ordering_index: str
        origin_country: str
        parent_product_id: str
        pattern: str
        post_conversion_signal_based_enforcement_appeal_eligibility: str
        price: str
        product_catalog: str
        product_feed: str
        product_group: str
        product_local_info: str
        product_type: str
        quantity_to_sell_on_facebook: str
        retailer_id: str
        retailer_product_group_id: str
        review_rejection_reasons: str
        review_status: str
        sale_price: str
        sale_price_end_date: str
        sale_price_start_date: str
        shipping_weight_unit: str
        shipping_weight_value: str
        short_description: str
        size: str
        start_date: str
        tags: str
        url: str
        video_fetch_status: str
        visibility: str
        wa_compliance_category: str
        additional_uploaded_image_ids: str
        android_app_name: str
        android_class: str
        android_package: str
        android_url: str
        checkout_url: str
        commerce_tax_category: str
        ios_app_name: str
        ios_app_store_id: str
        ios_url: str
        ipad_app_name: str
        ipad_app_store_id: str
        ipad_url: str
        iphone_app_name: str
        iphone_app_store_id: str
        iphone_url: str
        launch_date: str
        return_policy_days: str
        windows_phone_app_id: str
        windows_phone_app_name: str
        windows_phone_url: str
    class AgeGroup:
        adult: str
        all_ages: str
        infant: str
        kids: str
        newborn: str
        teen: str
        toddler: str
    class Availability:
        available_for_order: str
        discontinued: str
        in_stock: str
        mark_as_sold: str
        out_of_stock: str
        pending: str
        preorder: str
    class Condition:
        cpo: str
        new: str
        open_box_new: str
        refurbished: str
        used: str
        used_fair: str
        used_good: str
        used_like_new: str
    class Gender:
        female: str
        male: str
        unisex: str
    class ImageFetchStatus:
        direct_upload: str
        fetched: str
        fetch_failed: str
        no_status: str
        outdated: str
        partial_fetch: str
    class ReviewStatus:
        approved: str
        outdated: str
        pending: str
        rejected: str
    class ShippingWeightUnit:
        value_g: str
        kg: str
        lb: str
        oz: str
    class VideoFetchStatus:
        direct_upload: str
        fetched: str
        fetch_failed: str
        no_status: str
        outdated: str
        partial_fetch: str
    class Visibility:
        published: str
        staging: str
    class CommerceTaxCategory:
        fb_animal: str
        fb_animal_supp: str
        fb_aprl: str
        fb_aprl_accessories: str
        fb_aprl_athl_unif: str
        fb_aprl_cases: str
        fb_aprl_clothing: str
        fb_aprl_costume: str
        fb_aprl_cstm: str
        fb_aprl_formal: str
        fb_aprl_handbag: str
        fb_aprl_jewelry: str
        fb_aprl_shoe: str
        fb_aprl_shoe_acc: str
        fb_aprl_swim: str
        fb_aprl_swim_chil: str
        fb_aprl_swim_cvr: str
        fb_arts: str
        fb_arts_hobby: str
        fb_arts_party: str
        fb_arts_party_gift_card: str
        fb_arts_ticket: str
        fb_baby: str
        fb_baby_bath: str
        fb_baby_blanket: str
        fb_baby_diaper: str
        fb_baby_gift_set: str
        fb_baby_health: str
        fb_baby_nursing: str
        fb_baby_potty_trn: str
        fb_baby_safe: str
        fb_baby_toys: str
        fb_baby_transport: str
        fb_baby_transport_acc: str
        fb_bags: str
        fb_bags_bkpk: str
        fb_bags_boxes: str
        fb_bags_brfcs: str
        fb_bags_csmt_bag: str
        fb_bags_dffl: str
        fb_bags_dipr: str
        fb_bags_fnny: str
        fb_bags_grmt: str
        fb_bags_lugg: str
        fb_bags_lug_acc: str
        fb_bags_msgr: str
        fb_bags_tote: str
        fb_bags_trn_cas: str
        fb_bldg: str
        fb_bldg_acc: str
        fb_bldg_cnsmb: str
        fb_bldg_fence: str
        fb_bldg_fuel_tnk: str
        fb_bldg_ht_vnt: str
        fb_bldg_lock: str
        fb_bldg_matrl: str
        fb_bldg_plmb: str
        fb_bldg_pump: str
        fb_bldg_pwrs: str
        fb_bldg_str_tank: str
        fb_bldg_s_eng: str
        fb_bldg_tl_acc: str
        fb_bldg_tool: str
        fb_busind: str
        fb_busind_advertising: str
        fb_busind_agriculture: str
        fb_busind_automation: str
        fb_busind_heavy_mach: str
        fb_busind_lab: str
        fb_busind_medical: str
        fb_busind_retail: str
        fb_busind_sanitary_ct: str
        fb_busind_sign: str
        fb_busind_storage: str
        fb_busind_storage_acc: str
        fb_busind_work_gear: str
        fb_camera_acc: str
        fb_camera_camera: str
        fb_camera_optic: str
        fb_camera_optics: str
        fb_camera_photo: str
        fb_elec: str
        fb_elec_acc: str
        fb_elec_arcdade: str
        fb_elec_audio: str
        fb_elec_circuit: str
        fb_elec_comm: str
        fb_elec_computer: str
        fb_elec_gps_acc: str
        fb_elec_gps_nav: str
        fb_elec_gps_trk: str
        fb_elec_marine: str
        fb_elec_network: str
        fb_elec_part: str
        fb_elec_print: str
        fb_elec_radar: str
        fb_elec_sftwr: str
        fb_elec_speed_rdr: str
        fb_elec_television: str
        fb_elec_toll: str
        fb_elec_video: str
        fb_elec_vid_gm_acc: str
        fb_elec_vid_gm_cnsl: str
        fb_food: str
        fb_furn: str
        fb_furn_baby: str
        fb_furn_bench: str
        fb_furn_cart: str
        fb_furn_chair: str
        fb_furn_chair_acc: str
        fb_furn_divide: str
        fb_furn_divide_acc: str
        fb_furn_ent_ctr: str
        fb_furn_futn: str
        fb_furn_futn_pad: str
        fb_furn_office: str
        fb_furn_office_acc: str
        fb_furn_otto: str
        fb_furn_outdoor: str
        fb_furn_outdoor_acc: str
        fb_furn_sets: str
        fb_furn_shelve_acc: str
        fb_furn_shlf: str
        fb_furn_sofa: str
        fb_furn_sofa_acc: str
        fb_furn_storage: str
        fb_furn_tabl: str
        fb_furn_tabl_acc: str
        fb_generic_taxable: str
        fb_hlth: str
        fb_hlth_hlth: str
        fb_hlth_jwl_cr: str
        fb_hlth_lilp_blm: str
        fb_hlth_ltn_spf: str
        fb_hlth_prsl_cr: str
        fb_hlth_skn_cr: str
        fb_hmgn: str
        fb_hmgn_bath: str
        fb_hmgn_dcor: str
        fb_hmgn_emgy: str
        fb_hmgn_fplc: str
        fb_hmgn_fplc_acc: str
        fb_hmgn_gs_sft: str
        fb_hmgn_hs_acc: str
        fb_hmgn_hs_app: str
        fb_hmgn_hs_spl: str
        fb_hmgn_ktcn: str
        fb_hmgn_lawn: str
        fb_hmgn_lght: str
        fb_hmgn_linn: str
        fb_hmgn_lt_acc: str
        fb_hmgn_otdr: str
        fb_hmgn_pool: str
        fb_hmgn_scty: str
        fb_hmgn_smk_acc: str
        fb_hmgn_umbr: str
        fb_hmgn_umbr_acc: str
        fb_mdia: str
        fb_mdia_book: str
        fb_mdia_dvds: str
        fb_mdia_mag: str
        fb_mdia_manl: str
        fb_mdia_musc: str
        fb_mdia_prj_pln: str
        fb_mdia_sht_mus: str
        fb_offc: str
        fb_offc_bkac: str
        fb_offc_crts: str
        fb_offc_dskp: str
        fb_offc_eqip: str
        fb_offc_flng: str
        fb_offc_gnrl: str
        fb_offc_instm: str
        fb_offc_lp_dsk: str
        fb_offc_mats: str
        fb_offc_nm_plt: str
        fb_offc_ppr_hndl: str
        fb_offc_prsnt_spl: str
        fb_offc_sealr: str
        fb_offc_ship_spl: str
        fb_rlgn: str
        fb_rlgn_cmny: str
        fb_rlgn_item: str
        fb_rlgn_wedd: str
        fb_sftwr: str
        fb_sfwr_cmptr: str
        fb_sfwr_dgtl_gd: str
        fb_sfwr_game: str
        fb_shipping: str
        fb_spor: str
        fb_sport_athl: str
        fb_sport_athl_clth: str
        fb_sport_athl_shoe: str
        fb_sport_athl_sprt: str
        fb_sport_exrcs: str
        fb_sport_indr_gm: str
        fb_sport_otdr_gm: str
        fb_toys: str
        fb_toys_eqip: str
        fb_toys_game: str
        fb_toys_pzzl: str
        fb_toys_tmrs: str
        fb_toys_toys: str
        fb_vehi: str
        fb_vehi_part: str
    class ErrorPriority:
        high: str
        low: str
        medium: str
    class ErrorType:
        address_blocklisted_in_market: str
        aggregated_localization_issues: str
        app_has_no_aem_setup: str
        ar_deleted_due_to_update: str
        ar_policy_violated: str
        available: str
        bad_quality_image: str
        big_catalog_with_all_items_in_stock: str
        biz_msg_ai_agent_disabled_by_user: str
        cannot_edit_subscription_products: str
        catalog_not_connected_to_event_source: str
        checkout_disabled_by_user: str
        commerce_account_legal_address_invalid: str
        commerce_account_not_legally_compliant: str
        crawled_availability_mismatch: str
        da_disabled_by_user: str
        da_policy_violation: str
        deleted_item: str
        digital_goods_not_available_for_checkout: str
        duplicate_images: str
        duplicate_title_and_description: str
        empty_availability: str
        empty_condition: str
        empty_description: str
        empty_image_url: str
        empty_price: str
        empty_product_url: str
        empty_seller_description: str
        empty_title: str
        external_merchant_id_mismatch: str
        generic_invalid_field: str
        groups_disabled_by_user: str
        hidden_until_product_launch: str
        illegal_product_category: str
        image_fetch_failed: str
        image_fetch_failed_bad_gateway: str
        image_fetch_failed_file_size_exceeded: str
        image_fetch_failed_forbidden: str
        image_fetch_failed_link_broken: str
        image_fetch_failed_timed_out: str
        image_resolution_low: str
        inactive_shopify_product: str
        invalid_commerce_tax_category: str
        invalid_consolidated_locality_information: str
        invalid_content_id: str
        invalid_dealer_communication_parameters: str
        invalid_dma_codes: str
        invalid_fb_page_id: str
        invalid_images: str
        invalid_monetizer_return_policy: str
        invalid_offer_disclaimer_url: str
        invalid_offer_end_date: str
        invalid_pre_order_params: str
        invalid_range_for_area_size: str
        invalid_range_for_built_up_area_size: str
        invalid_range_for_num_of_baths: str
        invalid_range_for_num_of_beds: str
        invalid_range_for_num_of_rooms: str
        invalid_range_for_parking_spaces: str
        invalid_shelter_page_id: str
        invalid_shipping_profile_params: str
        invalid_subscription_disable_params: str
        invalid_subscription_enable_params: str
        invalid_subscription_params: str
        invalid_vehicle_state: str
        invalid_virtual_tour_url_domain: str
        inventory_zero_availability_in_stock: str
        in_another_product_launch: str
        item_group_not_specified: str
        item_not_shippable_for_sca_shop: str
        item_override_empty_availability: str
        item_override_empty_price: str
        item_override_not_visible: str
        item_price_not_positive: str
        item_stale_out_of_stock: str
        marketplace_disabled_by_user: str
        mini_shops_disabled_by_user: str
        missing_checkout: str
        missing_checkout_currency: str
        missing_color: str
        missing_country_override_in_shipping_profile: str
        missing_event: str
        missing_india_compliance_fields: str
        missing_shipping_profile: str
        missing_size: str
        missing_tax_category: str
        negative_community_feedback: str
        negative_price: str
        not_enough_images: str
        not_enough_unique_products: str
        no_content_id: str
        overlay_disclaimer_exceeded_max_length: str
        part_of_product_launch: str
        passing_multiple_content_ids: str
        product_dominant_currency_mismatch: str
        product_expired: str
        product_item_hidden_from_all_shops: str
        product_item_invalid_partner_tokens: str
        product_item_not_included_in_any_shop: str
        product_item_not_visible: str
        product_not_approved: str
        product_not_dominant_currency: str
        product_out_of_stock: str
        product_url_equals_domain: str
        property_price_currency_not_supported: str
        property_price_too_high: str
        property_price_too_low: str
        property_unit_price_currency_mismatch_item_price_currency: str
        property_value_contains_html_tags: str
        property_value_description_contains_off_platform_link: str
        property_value_format: str
        property_value_missing: str
        property_value_missing_warning: str
        property_value_non_positive: str
        property_value_string_exceeds_length: str
        property_value_string_too_short: str
        property_value_uppercase: str
        property_value_uppercase_warning: str
        purchase_rate_below_addtocart: str
        purchase_rate_below_viewcontent: str
        quality_duplicated_description: str
        quality_item_link_broken: str
        quality_item_link_redirecting: str
        retailer_id_not_provided: str
        shopify_invalid_retailer_id: str
        shopify_item_missing_shipping_profile: str
        shops_policy_violation: str
        subscription_info_not_enabled_for_feed: str
        tax_category_not_supported_in_uk: str
        unique_product_identifier_missing: str
        unmatched_events: str
        unsupported_product_category: str
        variant_attribute_issue: str
        video_fetch_failed: str
        video_fetch_failed_bad_gateway: str
        video_fetch_failed_file_size_exceeded: str
        video_fetch_failed_forbidden: str
        video_fetch_failed_link_broken: str
        video_fetch_failed_timed_out: str
        video_not_downloadable: str
        whatsapp_disabled_by_user: str
        whatsapp_policy_violation: str
    class MarkedForProductLaunch:
        value_default: str
        marked: str
        not_marked: str
    class OriginCountry:
        ad: str
        ae: str
        af: str
        ag: str
        ai: str
        al: str
        am: str
        an: str
        ao: str
        aq: str
        ar: str
        value_as: str
        at: str
        au: str
        aw: str
        ax: str
        az: str
        ba: str
        bb: str
        bd: str
        be: str
        bf: str
        bg: str
        bh: str
        bi: str
        bj: str
        bl: str
        bm: str
        bn: str
        bo: str
        bq: str
        br: str
        bs: str
        bt: str
        bv: str
        bw: str
        by: str
        bz: str
        ca: str
        cc: str
        cd: str
        cf: str
        cg: str
        ch: str
        ci: str
        ck: str
        cl: str
        cm: str
        cn: str
        co: str
        cr: str
        cu: str
        cv: str
        cw: str
        cx: str
        cy: str
        cz: str
        de: str
        dj: str
        dk: str
        dm: str
        do: str
        dz: str
        ec: str
        ee: str
        eg: str
        eh: str
        er: str
        es: str
        et: str
        fi: str
        fj: str
        fk: str
        fm: str
        fo: str
        fr: str
        ga: str
        gb: str
        gd: str
        ge: str
        gf: str
        gg: str
        gh: str
        gi: str
        gl: str
        gm: str
        gn: str
        gp: str
        gq: str
        gr: str
        gs: str
        gt: str
        gu: str
        gw: str
        gy: str
        hk: str
        hm: str
        hn: str
        hr: str
        ht: str
        hu: str
        id: str
        ie: str
        il: str
        im: str
        value_in: str
        io: str
        iq: str
        ir: str
        value_is: str
        it: str
        je: str
        jm: str
        jo: str
        jp: str
        ke: str
        kg: str
        kh: str
        ki: str
        km: str
        kn: str
        kp: str
        kr: str
        kw: str
        ky: str
        kz: str
        la: str
        lb: str
        lc: str
        li: str
        lk: str
        lr: str
        ls: str
        lt: str
        lu: str
        lv: str
        ly: str
        ma: str
        mc: str
        md: str
        me: str
        mf: str
        mg: str
        mh: str
        mk: str
        ml: str
        mm: str
        mn: str
        mo: str
        mp: str
        mq: str
        mr: str
        ms: str
        mt: str
        mu: str
        mv: str
        mw: str
        mx: str
        my: str
        mz: str
        na: str
        nc: str
        ne: str
        nf: str
        ng: str
        ni: str
        nl: str
        no: str
        np: str
        nr: str
        nu: str
        nz: str
        om: str
        pa: str
        pe: str
        pf: str
        pg: str
        ph: str
        pk: str
        pl: str
        pm: str
        pn: str
        pr: str
        ps: str
        pt: str
        pw: str
        py: str
        qa: str
        re: str
        ro: str
        rs: str
        ru: str
        rw: str
        sa: str
        sb: str
        sc: str
        sd: str
        se: str
        sg: str
        sh: str
        si: str
        sj: str
        sk: str
        sl: str
        sm: str
        sn: str
        so: str
        sr: str
        ss: str
        st: str
        sv: str
        sx: str
        sy: str
        sz: str
        tc: str
        td: str
        tf: str
        tg: str
        th: str
        tj: str
        tk: str
        tl: str
        tm: str
        tn: str
        to: str
        tr: str
        tt: str
        tv: str
        tw: str
        tz: str
        ua: str
        ug: str
        um: str
        us: str
        uy: str
        uz: str
        va: str
        vc: str
        ve: str
        vg: str
        vi: str
        vn: str
        vu: str
        wf: str
        ws: str
        xk: str
        ye: str
        yt: str
        za: str
        zm: str
        zw: str
    class WaComplianceCategory:
        country_origin_exempt: str
        value_default: str
    @classmethod
    def get_endpoint(cls): ...
    def api_create(self, parent_id, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def api_delete(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def api_get(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def api_update(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def get_channels_to_integrity_status(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def get_product_sets(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
    def get_videos_metadata(self, fields: Incomplete | None = None, params: Incomplete | None = None, batch: Incomplete | None = None, success: Incomplete | None = None, failure: Incomplete | None = None, pending: bool = False): ...
