from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class ProductFeedMissingFeedItemReplacement(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        home_listing: str = ...
        product_item: str = ...
        store_product_item: str = ...
        vehicle: str = ...
