from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class TargetingDynamicRule(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        field_action_type: str = ...
        ad_group_id: str = ...
        campaign_group_id: str = ...
        campaign_id: str = ...
        impression_count: str = ...
        page_id: str = ...
        post: str = ...
        retention_seconds: str = ...
