from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class TargetingGeoLocationMarket(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        country: str = ...
        key: str = ...
        market_type: str = ...
        name: str = ...
