from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class UserPaymentMobilePricepoints(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        mobile_country: str = ...
        phone_number_last4: str = ...
        pricepoints: str = ...
        user_currency: str = ...
