from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker
from typing import Any, Optional

class VehicleOffer(AbstractCrudObject):
    def __init__(self, fbid: Optional[Any] = ..., parent_id: Optional[Any] = ..., api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        amount_currency: str = ...
        amount_percentage: str = ...
        amount_price: str = ...
        amount_qualifier: str = ...
        applinks: str = ...
        body_style: str = ...
        cashback_currency: str = ...
        cashback_price: str = ...
        currency: str = ...
        dma_codes: str = ...
        downpayment_currency: str = ...
        downpayment_price: str = ...
        downpayment_qualifier: str = ...
        end_date: str = ...
        end_time: str = ...
        id: str = ...
        images: str = ...
        make: str = ...
        model: str = ...
        offer_description: str = ...
        offer_disclaimer: str = ...
        offer_type: str = ...
        price: str = ...
        sanitized_images: str = ...
        start_date: str = ...
        start_time: str = ...
        term_length: str = ...
        term_qualifier: str = ...
        title: str = ...
        trim: str = ...
        url: str = ...
        vehicle_offer_id: str = ...
        year: str = ...
    def api_get(self, fields: Optional[Any] = ..., params: Optional[Any] = ..., batch: Optional[Any] = ..., success: Optional[Any] = ..., failure: Optional[Any] = ..., pending: bool = ...): ...
