FROM golang:alpine

RUN apk add --no-cache \
    gcc \
    libc-dev \
    readline-dev

WORKDIR /app
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
RUN air -v

RUN go get -u github.com/nathany/looper