// Code generated by mockery v2.9.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	studiesmanager "github.com/vlab-research/vlab/dashboard-api/internal"
)

// StudySegmentsRepository is an autogenerated mock type for the StudySegmentsRepository type
type StudySegmentsRepository struct {
	mock.Mock
}

// GetAllTimeSegmentsProgress provides a mock function with given fields: ctx, studyId
func (_m *StudySegmentsRepository) GetAllTimeSegmentsProgress(ctx context.Context, studyId string) ([]studiesmanager.SegmentsProgress, error) {
	ret := _m.Called(ctx, studyId)

	var r0 []studiesmanager.SegmentsProgress
	if rf, ok := ret.Get(0).(func(context.Context, string) []studiesmanager.SegmentsProgress); ok {
		r0 = rf(ctx, studyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]studiesmanager.SegmentsProgress)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, studyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
