// Code generated by mockery v2.9.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	studiesmanager "github.com/vlab-research/vlab/dashboard-api/internal"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, userId
func (_m *UserRepository) CreateUser(ctx context.Context, userId string) (studiesmanager.User, error) {
	ret := _m.Called(ctx, userId)

	var r0 studiesmanager.User
	if rf, ok := ret.Get(0).(func(context.Context, string) studiesmanager.User); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Get(0).(studiesmanager.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
