from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdAccountContentFilterLevelsInheritance(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        an_business_ids: str = ...
        an_level: str = ...
        facebook_business_ids: str = ...
        facebook_level: str = ...
