from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdAccountAdVolume(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        actor_id: str = ...
        ads_running_or_in_review_count: str = ...
        current_account_ads_running_or_in_review_count: str = ...
