from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdAccountMatchedSearchApplicationsEdgeData(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        app_id: str = ...
        are_app_events_unavailable: str = ...
        icon_url: str = ...
        name: str = ...
        search_source_store: str = ...
        store: str = ...
        unique_id: str = ...
        url: str = ...
    class AppStore:
        amazon_app_store: str = ...
        does_not_exist: str = ...
        fb_android_store: str = ...
        fb_canvas: str = ...
        fb_gameroom: str = ...
        google_play: str = ...
        instant_game: str = ...
        itunes: str = ...
        itunes_ipad: str = ...
        roku_store: str = ...
        windows_10_store: str = ...
        windows_store: str = ...
