from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdAccountPromotableObjects(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        promotable_app_ids: str = ...
        promotable_page_ids: str = ...
        promotable_urls: str = ...
