from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdAccountRoas(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        adgroup_id: str = ...
        arpu_180d: str = ...
        arpu_1d: str = ...
        arpu_30d: str = ...
        arpu_365d: str = ...
        arpu_3d: str = ...
        arpu_7d: str = ...
        arpu_90d: str = ...
        campaign_group_id: str = ...
        campaign_id: str = ...
        date_start: str = ...
        date_stop: str = ...
        installs: str = ...
        revenue: str = ...
        revenue_180d: str = ...
        revenue_1d: str = ...
        revenue_30d: str = ...
        revenue_365d: str = ...
        revenue_3d: str = ...
        revenue_7d: str = ...
        revenue_90d: str = ...
        spend: str = ...
        yield_180d: str = ...
        yield_1d: str = ...
        yield_30d: str = ...
        yield_365d: str = ...
        yield_3d: str = ...
        yield_7d: str = ...
        yield_90d: str = ...
