from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdCreativeLinkDataImageLayerSpec(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        blending_mode: str = ...
        content: str = ...
        frame_image_hash: str = ...
        frame_source: str = ...
        image_source: str = ...
        layer_type: str = ...
        opacity: str = ...
        overlay_position: str = ...
        overlay_shape: str = ...
        scale: str = ...
        shape_color: str = ...
        text_color: str = ...
        text_font: str = ...
    class BlendingMode:
        lighten: str = ...
        multiply: str = ...
        normal: str = ...
    class FrameSource:
        custom: str = ...
    class ImageSource:
        catalog: str = ...
    class LayerType:
        frame_overlay: str = ...
        image: str = ...
        text_overlay: str = ...
    class OverlayPosition:
        bottom: str = ...
        bottom_left: str = ...
        bottom_right: str = ...
        center: str = ...
        left: str = ...
        right: str = ...
        top: str = ...
        top_left: str = ...
        top_right: str = ...
    class OverlayShape:
        circle: str = ...
        none: str = ...
        pill: str = ...
        rectangle: str = ...
        triangle: str = ...
    class TextFont:
        droid_serif_regular: str = ...
        lato_regular: str = ...
        noto_sans_regular: str = ...
        nunito_sans_bold: str = ...
        open_sans_bold: str = ...
        open_sans_condensed_bold: str = ...
        pt_serif_bold: str = ...
        roboto_condensed_regular: str = ...
        roboto_medium: str = ...
