from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdgroupRelevanceScore(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        negative_feedback: str = ...
        positive_feedback: str = ...
        score: str = ...
        status: str = ...
