from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker
from typing import Any, Optional

class AdReportSpec(AbstractCrudObject):
    def __init__(self, fbid: Optional[Any] = ..., parent_id: Optional[Any] = ..., api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        account_id: str = ...
        actions_group_by: str = ...
        creation_source: str = ...
        data_columns: str = ...
        date_preset: str = ...
        export_columns: str = ...
        filters: str = ...
        format_version: str = ...
        id: str = ...
        insights_section: str = ...
        name: str = ...
        report_schedule: str = ...
        report_schedule_id: str = ...
        sort_by: str = ...
        sort_dir: str = ...
        time_increment: str = ...
        time_interval: str = ...
        time_ranges: str = ...
    def api_get(self, fields: Optional[Any] = ..., params: Optional[Any] = ..., batch: Optional[Any] = ..., success: Optional[Any] = ..., failure: Optional[Any] = ..., pending: bool = ...): ...
