from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdRuleHistoryResultAction(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        action: str = ...
        field: str = ...
        new_value: str = ...
        old_value: str = ...
