from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdRuleExecutionOptions(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        field: str = ...
        operator: str = ...
        value: str = ...
    class Operator:
        equal: str = ...
        value_in: str = ...
