from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdRuleHistoryResult(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        actions: str = ...
        object_id: str = ...
        object_type: str = ...
    class ObjectType:
        ad: str = ...
        adset: str = ...
        campaign: str = ...
