from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AdsPixelStats(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        count: str = ...
        diagnostics_hourly_last_timestamp: str = ...
        event: str = ...
        value: str = ...
