from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class AudienceInsightsStudySpec(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        audience_definition: str = ...
        author_info: str = ...
        creation_time: str = ...
        end_time: str = ...
        excluded_rules: str = ...
        included_rules: str = ...
        start_time: str = ...
        status: str = ...
