from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker
from typing import Any, Optional

class AutomotiveModel(AbstractCrudObject):
    def __init__(self, fbid: Optional[Any] = ..., parent_id: Optional[Any] = ..., api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        applinks: str = ...
        automotive_model_id: str = ...
        availability: str = ...
        body_style: str = ...
        currency: str = ...
        custom_label_0: str = ...
        description: str = ...
        drivetrain: str = ...
        exterior_color: str = ...
        finance_description: str = ...
        finance_type: str = ...
        fuel_type: str = ...
        generation: str = ...
        id: str = ...
        images: str = ...
        interior_color: str = ...
        interior_upholstery: str = ...
        make: str = ...
        model: str = ...
        price: str = ...
        sanitized_images: str = ...
        title: str = ...
        transmission: str = ...
        trim: str = ...
        url: str = ...
        year: str = ...
    def api_get(self, fields: Optional[Any] = ..., params: Optional[Any] = ..., batch: Optional[Any] = ..., success: Optional[Any] = ..., failure: Optional[Any] = ..., pending: bool = ...): ...
