from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class CatalogItemAppealStatus(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        handle: str = ...
        item_id: str = ...
        status: str = ...
        use_cases: str = ...
