from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class ClientTransparencyStatus(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        grace_period_expiration_date: str = ...
        has_owning_business: str = ...
        is_satisfied: str = ...
        owning_business_requirements: str = ...
