from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class CommercePayout(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        amount: str = ...
        payout_date: str = ...
        payout_reference_id: str = ...
        status: str = ...
        transfer_id: str = ...
