from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class CreditPartitionActionOptions(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        liability_type: str = ...
        partition_type: str = ...
        send_bill_to: str = ...
