from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class CurrencyAmount(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        amount: str = ...
        amount_in_hundredths: str = ...
        currency: str = ...
        offsetted_amount: str = ...
