from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class Currency(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        currency_offset: str = ...
        usd_exchange: str = ...
        usd_exchange_inverse: str = ...
        user_currency: str = ...
