from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class DACheck(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        action_uri: str = ...
        description: str = ...
        key: str = ...
        result: str = ...
        title: str = ...
        user_message: str = ...
