from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class DayPart(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        days: str = ...
        end_minute: str = ...
        start_minute: str = ...
        timezone_type: str = ...
