from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class LeadGenConditionalQuestionsGroupChoices(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        customized_token: str = ...
        next_question_choices: str = ...
        value: str = ...
