from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class LiveVideoTargeting(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        age_max: str = ...
        age_min: str = ...
        excluded_countries: str = ...
        geo_locations: str = ...
