from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class Location(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        city: str = ...
        city_id: str = ...
        country: str = ...
        country_code: str = ...
        latitude: str = ...
        located_in: str = ...
        longitude: str = ...
        name: str = ...
        region: str = ...
        region_id: str = ...
        state: str = ...
        street: str = ...
        zip: str = ...
