from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class NativeOfferDiscount(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        currency: str = ...
        override: str = ...
        text: str = ...
        type: str = ...
        value1: str = ...
        value2: str = ...
