from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class OutcomePredictionPoint(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        actions: str = ...
        impressions: str = ...
        reach: str = ...
        spend: str = ...
