from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class Privacy(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        allow: str = ...
        deny: str = ...
        description: str = ...
        friends: str = ...
        networks: str = ...
        value: str = ...
