from facebook_business.adobjects.abstractcrudobject import AbstractCrudObject as AbstractCrudObject
from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from facebook_business.adobjects.objectparser import ObjectParser as ObjectParser
from facebook_business.api import FacebookRequest as FacebookRequest
from facebook_business.typechecker import TypeChecker as TypeChecker
from typing import Any, Optional

class Profile(AbstractCrudObject):
    def __init__(self, fbid: Optional[Any] = ..., parent_id: Optional[Any] = ..., api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        can_post: str = ...
        id: str = ...
        link: str = ...
        name: str = ...
        pic: str = ...
        pic_crop: str = ...
        pic_large: str = ...
        pic_small: str = ...
        pic_square: str = ...
        profile_type: str = ...
        username: str = ...
    class ProfileType:
        application: str = ...
        event: str = ...
        group: str = ...
        page: str = ...
        user: str = ...
    class Type:
        angry: str = ...
        care: str = ...
        haha: str = ...
        like: str = ...
        love: str = ...
        none: str = ...
        pride: str = ...
        sad: str = ...
        thankful: str = ...
        wow: str = ...
    def api_get(self, fields: Optional[Any] = ..., params: Optional[Any] = ..., batch: Optional[Any] = ..., success: Optional[Any] = ..., failure: Optional[Any] = ..., pending: bool = ...): ...
    def get_picture(self, fields: Optional[Any] = ..., params: Optional[Any] = ..., batch: Optional[Any] = ..., success: Optional[Any] = ..., failure: Optional[Any] = ..., pending: bool = ...): ...
