from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class ReachFrequencyActivity(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        account_id: str = ...
        campaign_active: str = ...
        campaign_started: str = ...
        creative_uploaded: str = ...
        io_approved: str = ...
        sf_link: str = ...
