from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class SplitTestWinner(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        ad_object_level: str = ...
        confidences: str = ...
        winner_ad_object_id: str = ...
