from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class StreamingReaction(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        count: str = ...
        reaction_type: str = ...
    class ReactionType:
        angry: str = ...
        care: str = ...
        haha: str = ...
        like: str = ...
        love: str = ...
        none: str = ...
        pride: str = ...
        sad: str = ...
        thankful: str = ...
        wow: str = ...
