from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class TargetingProductAudienceSpec(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        exclusions: str = ...
        inclusions: str = ...
        product_set_id: str = ...
