from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class UserPaymentMethodsInfo(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        account_id: str = ...
        available_card_types: str = ...
        available_payment_methods: str = ...
        available_payment_methods_details: str = ...
        country: str = ...
        currency: str = ...
        existing_payment_methods: str = ...
