from facebook_business.adobjects.abstractobject import AbstractObject as AbstractObject
from typing import Any, Optional

class VideoCopyrightSegment(AbstractObject):
    def __init__(self, api: Optional[Any] = ...) -> None: ...
    class Field(AbstractObject.Field):
        duration_in_sec: str = ...
        media_type: str = ...
        start_time_in_sec: str = ...
