from typing import Any

class FacebookError(Exception): ...

class FacebookRequestError(FacebookError):
    def __init__(self, message: Any, request_context: Any, http_status: Any, http_headers: Any, body: Any) -> None: ...
    def request_context(self): ...
    def http_status(self): ...
    def http_headers(self): ...
    def body(self): ...
    def api_error_message(self): ...
    def api_error_code(self): ...
    def api_error_subcode(self): ...
    def api_error_type(self): ...
    def api_blame_field_specs(self): ...
    def api_transient_error(self): ...
    def get_message(self): ...

class FacebookBadObjectError(FacebookError): ...
class FacebookBadParameterError(FacebookError): ...
class FacebookUnavailablePropertyException(FacebookError): ...

class DocsmithSkipTestError(Exception):
    def __init__(self, message: Any) -> None: ...
    def get_skip_error_msg(self): ...

class FacebookBadParameterTypeException(FacebookError): ...
