from typing import Any, Optional

class FacebookSession:
    GRAPH: str = ...
    app_id: Any = ...
    app_secret: Any = ...
    access_token: Any = ...
    proxies: Any = ...
    timeout: Any = ...
    debug: Any = ...
    requests: Any = ...
    def __init__(self, app_id: Optional[Any] = ..., app_secret: Optional[Any] = ..., access_token: Optional[Any] = ..., proxies: Optional[Any] = ..., timeout: Optional[Any] = ..., debug: bool = ...) -> None: ...
