from facebook_business.exceptions import FacebookBadParameterTypeException as FacebookBadParameterTypeException
from facebook_business.utils import api_utils as api_utils
from typing import Any

class TypeChecker:
    primitive_types: Any = ...
    def __init__(self, type_check_info: Any, type_check_enum: Any) -> None: ...
    def is_primitive_type(self, type: Any): ...
    def convert_string_to_prim_type(self, primitive_type: Any, value: Any): ...
    def get_type(self, param: Any): ...
    def is_valid_key(self, param: Any): ...
    def is_valid_pair(self, param: Any, value: Any): ...
    def is_type(self, value_type: Any, value: Any, allow_dict_as_obj: bool = ...): ...
    def is_type_collection(self, value_type: Any, collection_name: Any): ...
    def get_type_from_collection(self, value_type: Any, collection_name: Any): ...
    def is_list_param(self, param: Any): ...
    def is_map_param(self, param: Any): ...
    def is_file_param(self, param: Any): ...
    def get_typed_value(self, key: Any, value: Any): ...
