version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - migrations
    networks:
      - api
    volumes:
      - .:/src/app
      # Needed for the dependency on the inference modules
      # for types
      - ../inference:/src/inference
    entrypoint: air
  conf_api:
    build:
      context: ../adopt
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3500:8000
    depends_on:
      - migrations
    networks:
      - api
    entrypoint:
      - uvicorn
      - adopt.server.server:app
      - "--host=0.0.0.0"
  cockroachdb:
    image: cockroachdb/cockroach:v21.2.3
    entrypoint: cockroach start-single-node --insecure --advertise-addr localhost
    ports:
      - "5432:26257"
    networks:
      - api
  migrations:
    image: migrate/migrate:v4.15.2
    volumes:
      - ../devops/migrations:/migrations
      - ../devops/seeds:/seeds
    entrypoint: |
      ash -c '
        migrate  \
        -database cockroach://root@cockroachdb:26257/defaultdb?sslmode=disable \
        -path /migrations/initvlab \
        up 1
        migrate  \
        -database cockroach://root@cockroachdb:26257/vlab?sslmode=disable \
        -path /migrations \
        up
        migrate  \
        -database "cockroach://root@cockroachdb:26257/vlab?sslmode=disable&x-migrations-table=seeds" \
        -path /seeds \
        up
        '
    depends_on:
      - cockroachdb
    networks:
      - api
networks:
  api:
