name: adopt

on:
  pull_request:
    paths:
      - 'adopt/**'
      - '.github/workflows/adopt.yaml'
  push:
    branches: [main]
    paths:
      - 'adopt/**'
      - '.github/workflows/adopt.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: adopt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install poetry
      - run: make test-db
      - run: poetry install
      - run: make test
