name: inference

on:
  pull_request:
    paths:
      - 'inference/**'
      - '.github/workflows/inference.yaml'
  push:
    branches: [main]
    paths:
      - 'inference/**'
      - '.github/workflows/inference.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inference
    env:
      PG_URL: postgres://root@localhost:5433/test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - run: make test-db
      - run: make test
